### PR TITLE
Added show member roles

### PR DESCRIPTION
**Pull request by jacemonje**
Redoing https://github.com/Growstuff/growstuff/pull/735 and to answer issue #557 

Will add the test; I'm still trying to figure out a better implementation.

### CODE REVIEW

**Comment by cesy** [comment]
Thanks for starting work on this.

**Comment by pozorvlak** [comment]
I think the implementation's fine, this just needs some tests.

**Comment by pozorvlak** [comment]
@jacemonje sorry, but view tests are deprecated! Please rewrite it as a feature test.

**Comment by cesy** [comment]
Closing as superseded by #787 that has the same thing with tests added.

**Pull request closed without merging**
