### PR TITLE
Release 17

### PR DESCRIPTION
**Pull request by cesy**
Let's get some more stuff live.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
I'd be keen to deploy this lot before merging too much more; keep the momentum going.

**Comment by Br3nda** [comment]
Ship it!

**Comment by Br3nda** [comment]
Should we merge master into here? There's commits in master that never got back to dev branch.

**Comment by cesy** [comment]
It looks like the only missing commits are merge commits, but please do check and make a pull request in case if we've missed anything.

**Pull request merged**
