### PR TITLE
WIP - json api with oauth

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by homu-gs** [comment]
:umbrella: The latest upstream changes (presumably #1055) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by cesy** [comment]
This looks broadly sensible, I'd be happy to merge once the conflicts are sorted.

**Comment by Br3nda** [comment]
I'm going to add Applications having owners. Right not it's wide open for anonymous users to create (or delete!) apps

**Comment by Br3nda** [comment]
closing -- will come back to this...

**Pull request closed without merging**
