### PR TITLE
Update rails to 4.2.0+

### PR DESCRIPTION
**Pull request by CloCkWeRX**
And a few other minor bits and pieces.

We get access to all of this:
http://edgeguides.rubyonrails.org/4_2_release_notes.html

... which is vaguely handy.

Specifics:
 * Upgrade activemerchant and unvendor, so we're no longer pinned to a 2 year old version
 * Upgrade rails
 * Fix deprecation errors relating to activerecord.find (we could certainly apply those separately if its cleaner)
 * Fix deprecation errors with active_job vs deliver (defaults to deliver_now)
 * Fix deprecation errors with view tests using old selectors with ```assert_select```, now that things are based on nokogiri
 * Rewrite 2-3 tests slightly, to relax expectations around rendering specific asset names as img src="..." or to better focus on the behaviour over implementation
 * Fix devise 4.2 deprecation errors. I have no idea why I didn't notice these in the previous pull request / didn't think we were affected, but they were appearing frequently.

### CODE REVIEW

**Comment by maco** [comment]
Sweet, weren't we just talking about how it'd be nice for mail to send
later if needed?

**Comment by CloCkWeRX** [comment]
I think I might tackle
```
/home/clockwerx/growstuff/spec/rails_helper.rb:7:in `<top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead). (called from included at /home/clockwerx/growstuff/vendor/gems/active_utils-1.0.5/lib/active_utils/common/posts_data.rb:5)
DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead). (called from included at /home/clockwerx/growstuff/vendor/gems/active_utils-1.0.5/lib/active_utils/common/posts_data.rb:11)
DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead). (called from included at /home/clockwerx/growstuff/vendor/gems/active_utils-1.0.5/lib/active_utils/common/posts_data.rb:14)
DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead). (called from included at /home/clockwerx/growstuff/vendor/gems/active_utils-1.0.5/lib/active_utils/common/posts_data.rb:17)
DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead). (called from included at /home/clockwerx/growstuff/vendor/gems/active_utils-1.0.5/lib/active_utils/common/posts_data.rb:18)
DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead). (called from <class:Gateway> at /home/clockwerx/growstuff/vendor/gems/activemerchant-1.33.0/lib/active_merchant/billing/gateway.rb:104)
```

Tomorrow morning

**Comment by CloCkWeRX** [comment]
Well, that's a bit frightening: 40% of our coverage came from external libraries!

**Comment by CloCkWeRX** [comment]
This one is finally ready - ```Request to 'http://localhost:8081/crops/magic-bean' failed to reach server, check DNS and/or server status``` is just a flakey test :)

**Comment by homu-gs** [comment]
:umbrella: The latest upstream changes (presumably #974) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by maco** [comment]
(in case @pozorvlak 's change to travis config recently fixed that localhost:8081 thing)

**Comment by CloCkWeRX** [comment]
They might have, but a few other PR's have come along that do parts of what is proposed here. Remind me to redo this on current dev shortly.

**Pull request closed without merging**
