### PR TITLE
Covert all tabs to spaces

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by Br3nda** [comment]
" Request to 'http://localhost:8081/crops/magic-bean' failed to reach server,"

These tests are a bit flaky...

**Comment by homu-gs** [comment]
:umbrella: The latest upstream changes (presumably #1059) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by Br3nda** [comment]
Another flaky resolve localhost dns error.
Otherwise the tests all pass.

**Comment by pozorvlak** [comment]
@Br3nda: yes, yes they are :-( See issue #901.

**Pull request merged**
