### PR TITLE
Deployment from Travis builds

### PR DESCRIPTION
**Pull request by pozorvlak**
A stab at #491. If you click "merge" on this PR then it *should* deploy recent changes to growstuff-staging and run migrations and the current deploy-tasks.sh. I haven't tested it on the dev branch, but [here's an example of it successfully deploying to my sandbox app](https://travis-ci.org/Growstuff/growstuff/builds/47582713).

This doesn't totally meet the spec, unfortunately:

 - it doesn't turn maintenance mode on for the duration of deployments (see https://travis-ci.org/Growstuff/growstuff/builds/47577519 and https://travis-ci.org/Growstuff/growstuff/builds/47580792 for two failed attempts at doing this). http://xseignard.github.io/2013/02/18/continuous-deployement-with-github-travis-and-heroku-for-node.js/ suggests a possible approach to turning on maintenance mode, but that looks unpleasantly hand-rolled.
 - it doesn't set environment variables on the heroku dynos (the `figaro` step in [the release management guidelines](http://wiki.growstuff.org/index.php/Release_management#Deploying_new_features_to_staging)), because I'm not sure how to expose them to Travis securely. Perhaps we could use [Travis' secure variables](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables)? Not sure how that would work, TBH.

I've left the code in for deploying the `travis_deploy` branch to http://tranquil-basin-3130.herokuapp.com, which is an instance of Growstuff running on my Heroku account. We'll want to remove it eventually, but I suspect we'll need a deployment sandbox while we work through the issues on this PR :-)

### CODE REVIEW

**Comment by tygriffin** [comment]
1. Being able to turn maintenance mode on would be nice, but indeed looks like a headache. I wouldn't worry about it.

2. Looks like Travis Secure Variables wouldn't work with PR's coming from a fork. This means that someone with greater privileges must manually do the deploy when something in the "secrets" (soon to be secrets.yml, I believe) changes just like we're doing now, which seems right to me. I'd leave this one be as well.

**Comment by Skud** [comment]
Maintenance mode doesn't really matter for staging, but I would definitely like to use it on production.

**Comment by pozorvlak** [comment]
Oops, looks like I opened this from the wrong place. I'll close it and re-open it from my fork.

**Comment by pozorvlak** [comment]
It would be nice if we could at least add an automatic "has the list of
environment variables changed" check.

**Pull request closed without merging**
