### PR TITLE
Use presence instead of regex validation

### LINKED ISSUE #1252: Fix "validation_regex" issue in app/models/post.rb
Insufficient validation for 'subject' using /\S/. Use \A and \z as anchors

https://codeclimate.com/github/Growstuff/growstuff/app/models/post.rb#issue_58b5f663969465000100016f

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #1252

### CODE REVIEW

**Comment by arun1595** [comment]
@Br3nda We already have a couple of specs to assert the correctness of the `presence` validation.

[L64](https://github.com/Growstuff/growstuff/blob/dev/spec/models/post_spec.rb#L64)
[L69](https://github.com/Growstuff/growstuff/blob/dev/spec/models/post_spec.rb#L69)

**Comment by arun1595** [comment]
@Br3nda LOL I understand the comment and the spec description. It was strange at first.

Didn't even have to `git blame`  :wink:

context: https://github.com/Growstuff/growstuff/blob/dev/spec/models/post_spec.rb#L92

**Comment by Br3nda** [comment]
There's a git conflict with the README.md. This is caused by another new contributor adding their name on the same line. you'll need to resolve and push again

**Comment by arun1595** [comment]
@Br3nda Done.

**Comment by Br3nda** [comment]
thank you for this contribution to growstuff, @arun1595  - hope you can contribute again.

**Comment by arun1595** [comment]
@Br3nda Sure, would love to. Can you point me to an issue that might be a good fit for me?

**Comment by Br3nda** [comment]
@arun1595 how about #514  ?

**Comment by arun1595** [comment]
@shiny Okay. I will take it. Assign me to it if you can. 

By the way, do we have a gitter channel where we have discussions or any other medium?

I am asking because since I am new to the project, I would like to get myself oriented quickly and having a medium for communication(other than github) would be nice. I don't want to flood the issue thread with my (trivial) questions :wink:

**Comment by Br3nda** [comment]
Gitter is here: https://gitter.im/Growstuff/growstuff
but it's pretty quiet.

**Pull request merged**
