### PR TITLE
DRY up photo & model interaction

### PR DESCRIPTION
**Pull request by maco**
* move stuff in models into a concern
 * create combined collection for all models that have photos

I'm marking this WIP because I think a constants file that maps garden/gardens/Garden would make it possible to minimize repetition in `photos_controller.rb` too. I want to minimize how many places we need to touch on adding a new model-that-uses-photos because I know missing a copy&paste has introduced bugs before. (The particular past bug I'm thinking of is handled by this commit, though, with the `self.destroy unless relationships.size > 0`)

### CODE REVIEW

**Comment by Br3nda** [comment]
just needs the rubocop fixes.

**Comment by maco** [comment]
I kind of want to add a constants file that makes a hash with garden/gardens/Garden etc so that in `photos_controller.rb` we can look up class_name versus relation_name etc. and eliminate the case statements (which are a place I'd expect to see a bug crop up with adding photos to another model). What's here so far does at least eliminate having that bug we had before: forgot to list the new model in `destroy_if_unused`

**Comment by maco** [comment]
Ok, rubocop doesn't like that I'm using `has_and_belongs_to_many` in photo_capable.rb and wants me to do `has_many ___, through: ____` instead. And I *could* have it use the class name to work out the join table model's name (and create those models)...**if** it weren't for the fact that they're named PhotosPlantings, GardensPhotos, and HarvestsPhotos. Yeah, oops. They're in opposite orders (I think skud maybe said do them alphabetically?). So, if I rename the PhotosPlantings table to PlantingsPhotos, and add 3 models, then I could make rubocop happy here...or I could tell rubocop to look away.

Thoughts?

**Comment by Br3nda** [comment]
you can ignore on that one line
`# rubocop:disable Rails/HasAndBelongsToMany`

**Comment by maco** [comment]
I finally figured it out!!! 🎉

**Comment by pozorvlak** [comment]
Possible flaky test failure:

```
) CropsController GET crop search fetches the crop search page
     Failure/Error: return response.records.to_a
     Elasticsearch::Transport::Transport::Errors::ServiceUnavailable:
       [503] {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed]","status":503}
     # ./app/models/crop.rb:314:in `search'
     # ./app/controllers/crops_controller.rb:68:in `search'
     # ./spec/controllers/crops_controller_spec.rb:45:in `block (3 levels) in <top (required)>'
```

Rerunning now. I *really* wish Travis kept logs around from jobs that have been re-run.

**Comment by pozorvlak** [comment]
The build [passed on re-running](https://travis-ci.org/Growstuff/growstuff/jobs/180104523) :-(

**Comment by maco** [comment]
That's bad news for our CI but good news for me

**Pull request merged**
