### PR TITLE
Garden Timeline

### PR DESCRIPTION
**Pull request by Br3nda**
Adds timeline to gardens#show. Should be merged after #1514 
image

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
```
 Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       SyntaxError: JSON Parse error: Unrecognized token '<'
       SyntaxError: JSON Parse error: Unrecognized token '<'
           at http://localhost:8081/assets/charts-1c341fddc0188b2419b74b3bcead385bba0b4ef47432426479a0a465c67724e4.js:18826 in parse
           at http://localhost:8081/assets/charts-1c341fddc0188b2419b74b3bcead385bba0b4ef47432426479a0a465c67724e4.js:18826 in onload
```

**Comment by Br3nda** [comment]
i'm getting those on the rails 5 PR too... i haven't been able to find the source

**Comment by CloCkWeRX** [comment]
Ah so close, green for a second there!

**Comment by CloCkWeRX** [comment]
```
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       Error: No adapter found
       Error: No adapter found
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:20099 in callAdapter
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:20077 in renderChart
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:20322 in callback
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:18837 in errorCatcher
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:18848
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:41205 in fire
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:41335 in fireWith
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:47813 in done
           at http://localhost:8081/assets/application-a2296633c30e0229ac92f23f3c3946c23c82c7ac345fcb385c1b206156d33672.js:48284 in callback
```

**Comment by Br3nda** [comment]
Just realised I only have finished plantings on the timeline
I'd added plantings that have a predicted finish date

**Comment by Br3nda** [comment]
i think i can do the same for harvests --- so it's easier to see and remember when your fruit trees are gonna be fruiting.

**Comment by Br3nda** [comment]
Future events, on the timeline
image

**Comment by pozorvlak** [comment]
This is very exciting!

**Pull request merged**
