### PR TITLE
Fixes #720 - Places show nearby seeds, members, and plantings.

### LINKED ISSUE #720: "Places" page should show plantings, harvests, seeds, etc
It would be cool if http://growstuff.org/places/melbourne could show stuff other than members near here.  For instance:

* what is growing/being harvested near here
* what seeds are available near here

In future we might even show seed retailers, and things like that.

I'd like to see a mockup/wireframe before implementation of this!

### PR DESCRIPTION
**Pull request by GabrielSandoval**
OLD places page:
screen shot 2015-07-07 at 1 26 34 pm

NEW places page:
screen shot 2015-07-07 at 1 34 46 pm

Hi @pozorvlak and @maco ,

I added nearby seeds and plantings in addition to nearby members as a result when searching for a place (see image above). I also created the feature tests on this.

I'll be waiting for your response.

Gabriel Sandoval,
AELOGICA Intern

### CODE REVIEW

**Comment by pozorvlak** [comment]
I don't really like the "#" column in the plantings list - does it do anything, like serve as a permalink? If not, I think you should delete it. Otherwise, cool!

**Comment by GabrielSandoval** [comment]
Okay, I'll remove them from the plantings/_thumbnail.

**Comment by GabrielSandoval** [comment]
I've removed the '#'s from the plantings/_thumbnail partial itself and fixed all the other templates affected (gardens/show page, planting/index, members/_garden partial)

screen shot 2015-07-08 at 10 40 45 am

**Comment by maco** [comment]
To make it cleaner and more card-y, how about removing the column headers
"Photo" and "Planting Details"?

**Comment by pozorvlak** [comment]
Awesome! I agree that the column headers should be removed too.

**Comment by GabrielSandoval** [comment]
Will do.

**Comment by GabrielSandoval** [comment]
Looks neat now.

screen shot 2015-07-09 at 8 03 29 am

**Comment by pozorvlak** [comment]
This is starting to look really good! It's a bit stretched-out horizontally, though - could you try putting the plantings thumbnails in a Bootstrap grid?

**Comment by GabrielSandoval** [comment]
UPDATE:

Small screens:
screen shot 2015-07-10 at 3 07 50 pm

Large screens:
screen shot 2015-07-10 at 3 08 11 pm

**Comment by maco** [comment]
Looks much nicer

**Comment by pozorvlak** [comment]
Excellent!

**Comment by GabrielSandoval** [comment]
Thank you so much @maco and @pozorvlak ! Feels nice to be able to contribute. :)

**Pull request merged**
