### PR TITLE
Remove "show" methods that just do the default

### PR DESCRIPTION
**Pull request by pozorvlak**
We can just fall back to the default implementation for these.

See comments on #972 for background.

### CODE REVIEW

**Comment by maco** [comment]
since our coverage is now suspect, we should check that html and ison are both covered by the super show

**Comment by pozorvlak** [comment]
@maco: excellent point.

**Comment by pozorvlak** [comment]
Oh look, a "PhantomJS client died" error: https://travis-ci.org/Growstuff/growstuff/jobs/136173245#L2088 Paging #901...

**Comment by CloCkWeRX** [comment]
Will merge after tests go green

**Pull request merged**
