### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by cesy**
Update to all the latest fixes that we've done

- [x] Regression test https://github.com/Growstuff/growstuff/issues/2743
- [x] General login and navigation tests
- [x] Spot check on mobile and browser (members page) - https://www.staging.growstuff.org/members/clockwerx/gardens not terrible
- [ ] If possible, check or fix email sending?

Next deploy
- [ ] Regression test https://github.com/Growstuff/growstuff/issues/2717
- [ ] Regression test https://github.com/Growstuff/growstuff/issues/2847
- [ ] Regression test https://github.com/Growstuff/growstuff/issues/907 ?

Post deploy
- [ ] https://github.com/Growstuff/growstuff/issues/2527 Revise this content

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Ugh, I have no idea why heroku does this:
```
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
###### WARNING:
       Your app was upgraded to bundler 1.17.3.
       Previously you had a successful deploy with bundler 2.3.25.
       
       If you see problems related to the bundler version please refer to:
       https://devcenter.heroku.com/articles/bundler-version#known-upgrade-issues
 ```

**Comment by CloCkWeRX** [comment]
https://github.com/heroku/heroku-buildpack-ruby/pull/1341

**Comment by cesy** [comment]
Right, so we either have to downgrade Ruby, or wait for Heroku to merge that and fix their issue. I'm inclined to wait.

**Comment by CloCkWeRX** [comment]
I really hate Heroku.

```
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/ruby
-----> Ruby app detected
-----> Installing bundler 1.17.3
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
###### WARNING:
       Your app was upgraded to bundler 1.17.3.
       Previously you had a successful deploy with bundler 2.3.25.
 ```

WHY WOULD YOU "UPGRADE" US TO A LOWER VERSION!
Particularly when you have known bugs:
https://devcenter.heroku.com/articles/bundler-version#bundler-2-2-3

**Comment by CloCkWeRX** [comment]
I am tempted to say let's merge as is, even if mail isn't happy yet. Variety of security fixes; etc.

**Review by CloCkWeRX — APPROVED** [review]

**Comment by cesy** [comment]
Yeah, let's go for it, it's still a significant improvement.

**Pull request merged**
