### PR TITLE
Update public error pages

### PR DESCRIPTION
**Pull request by meganft**
This is initial rerender of custom error pages, written in html since they are static served. Just rooted back to main page. Please let me know what changes you'd like!

### CODE REVIEW

**Comment by Br3nda** [comment]
I resolved the merge conflict here -- but it need one more thing.
@meganft  can you run `bundle install` and push again?

**Comment by CloCkWeRX** [comment]
Might need to pick out the relevant commits and rebase; so it cleanly applies/merges

**Comment by Br3nda** [comment]
I've rebased this branch over at #1258

**Comment by Br3nda** [comment]
Merge as part of #1280

**Pull request closed without merging**
