### PR TITLE
Notify members when mentioned in a post

### PR DESCRIPTION
**Pull request by sksavant**
Feature #505 

Depends on changes in PR #824

### CODE REVIEW

**Comment by cesy** [comment]
As much as possible we aim to use feature specs rather than model/view/controller specs these days.

**Comment by cesy** [comment]
Test are all failing with things like:
Failure/Error: @post2 = FactoryGirl.create(:post, :created_at => 1.minute.ago)
     NameError:
       uninitialized constant Haml::Filters::GrowstuffMarkdown::MEMBER_REGEX

If you want to rebase once the other stuff is merged, that'll kick off another Travis build.

**Comment by pozorvlak** [comment]
@cesy: I thought we were replacing view and controller specs with feature tests, but continuing to test model code with unit tests? That makes more sense to me - the model layer should make sense and be testable independently of a browser.

**Comment by sksavant** [comment]
Merged latest dev branch.
I too was under the impression from [this talk page](http://talk.growstuff.org/t/changes-to-our-development-environment/97) that only controller and view specs are deprecated

**Comment by cesy** [comment]
Hmm, yeah, that talk post does align - I must have misunderstood, and @pozorvlak's argument for the reasoning makes sense. And the tests are passing now, and code looks okay on a skim-through, so happy to merge if @pozorvlak agrees.

**Comment by pozorvlak** [comment]
Looks good to me!

**Pull request merged**
