### PR TITLE
Bar graphs -- initial draft pull request

### PR DESCRIPTION
**Pull request by Marlena**
This is a draft pull request of bar charts, suggested by @tygriffin, for sunniness and plantings and is not meant to be merged in, but just to show what's been done.  This post will go over some of the big pieces in the pull request and also detail some of the work that's left.

Here is a link to the initial [Tracker story](https://www.pivotaltracker.com/story/show/53219527).
## To see the chart in action

Open a crops page.

screen shot 2015-02-01 at 7 58 05 am
## Design

This example is the MVP I've been working towards.  

horizontal_chart_example
## Javascript

These charts are being written in javascript with an emphasis on declarative over imperative style.  This is why information about what the charts should look like is stored in json data.  The javascript was written with the help of local pair, Ryan Dy ([rdy](https://github.com/rdy)) who writes javascript, node and react.js code all day, everyday for Pivotal Labs.  Big thanks to rdy!
## Component Architecture

While the higher level structure is a horizontal bar graph, the underlying pieces could be used for other types of graphs.  Some refactoring is needed as I was developing my understanding of component based architecture while building this.
## Usage

The charts are designed to be easy to reuse in different areas of Growstuff.  See crops.js.erb for usage.
## D3

The charts are rendered as svg by D3.  While D3 is a widely used library for visualization, it does not necessarily promote good software engineering practices.  Often, the code for a chart looks like one messy chain of method calls and it's hard to tell what part each call plays in the chart.  I did a lot of work to break the code for the chart into more digestible objects and to make what each object is doing clearer for easier maintenance.  The side effect of this is that you can also see how to approach OO in javascript with classes and objects.
## Jasmine Tests & TDD

Although this started as a messy spike in a personal repo, all of the code in the Growstuff repo was test driven with [Jasmine](http://jasmine.github.io/).

To run the tests: rake jasmine

Jasmine will then print out a URL you can paste into a browser to see the tests.  By clicking on a test, you can see Jasmine run that one test.  If you open the browser inspector, you can see the page content under test rendered in the jasmine-content div.
## Still working on
- Numbers indicating the total for each category
- Currently, the data you see on the chart is fake.  There will need to be access to the sunniness and planting data
- What to do about the empty category:  Some people don't fill out either the sunniness or planting data.  Does this category belong on the chart?
- Style of this area on the crops page and location on the crops page

In order to keep myself moving and focused, I created a public [Tracker project](https://www.pivotaltracker.com/n/projects/1265590).  This helped me break down each step and keep track of the different tests that needed to be written and different small pieces to be added to the charts.  
## Extras that can happen separately from this feature work
- Design changes
- Axis marks along the x and y scale

### CODE REVIEW

**Comment by pozorvlak** [comment]
Wow, awesome! I'm not awake enough to review this properly, but from a quick skim it looks really impressive. Well done!

**Comment by yoongkang** [comment]
That's really cool!

**Comment by tygriffin** [comment]
This looks really nice! Great work! Here's my input:

1. Can you add comments at the top of each file under `/graphs` explaining what the file is for generally? It might be nice to have such comments above each function, since - like you mentioned before - the D3 API is so hard to look at.

2. This PR brings up a good point about Javascript testing. We should probably have a little discussion about this, but I think the way you've done testing is a great model. Jasmine is a great choice.

3. We're having [a discussion about how to organize Javascript](http://talk.growstuff.org/t/javascript-frameworks/195/23) over on Talk. Eventually we might wrap this graphing stuff in some kind of component that takes the JSON configuration object that you mentioned and renders the graph. If we use something like ReactJS this could open up nice possibilities for a component that re-renders whenever the underlying data model changes. Creating this component shouldn't necessarily block this PR, but just something to think about.

4. At this stage it might also be a good idea to think about what kind of graphing requirements Growstuff has generally. From @Skud's [great wireframes](http://talk.growstuff.org/t/aspirational-wireframes-for-the-crop-detail-page/204), it looks like we'll just be using some variation of a bar graph most of the time. If that's the case then I think we're more than halfway there with this PR. However, if we need lots of different kinds of graphs (pie, stacked bar, combination graphs, etc) and extra stuff like responsive layouts and tooltips, then it might be a good idea to investigate a higher level tool that sits on top of D3. @Marlena, correct me if I'm wrong, but D3 is pretty low level stuff. 

5. You might want to take a look at Highcharts API. Just like your declarative style, Highcharts graphs are created using a JSON object as configuration. I believe we can't use Hightcharts because of the kind of license they use, but it might be a good model. I think you could probably improve on their API in some ways as well though :)

6. What are your thoughts on passing the data into the graph? We should decide on some standard format. Highcharts accepts data as either a collection of two element arrays or a collection of objects with x and y keys.

**Comment by Marlena** [comment]
I see the comment about using D3 for this feature.  It has taken me a while to process how to answer the issue raised about D3 in this pull request.  This is one of those situations where I don't think a pull request is ideal, but I'm doing my best below to lay things out so that I can finish this feature (and I am SO ready to finish this feature.)

Since D3 is fundamental to this pull request, I'd like to address this first.  

I'm guessing, @tygriffin , that you haven't seen the [Tracker story](https://www.pivotaltracker.com/story/show/53219527) for this feature.  It is worth taking a look at that story and also a look at the comments.

screen shot 2015-02-13 at 6 45 22 am

What you will see is that when @Skud  and I originally discussed this feature, we talked about it being written using D3.  In fact, one of the earliest comments in the Tracker story mentions this.  There are a few comments in the Tracker story because I continued working on these graphs in D3 and the usage of D3 wasn't questioned.

Several months later, I have a good grasp of D3.  The code I've written organizes the D3 into bite sized chunks using components that could be reused and there are tests for each part of the graph.  

For this reason, I consider removing D3 out of scope for this particular pull request.  In light of the Tracker story and all of the communication that happened with this feature, this should not be a surprise and, I'm hoping, is not a problem for moving forward.

However, the future is coming and it looks like React.js components such as this one: http://react-components.com/component/react-horizontal-bar-chart

Also, it is possible that multiple graphing frameworks could be useful for Growstuff. I could see using a combination of High charts, D3, React components, Raphael or whatever depending on the visualization needs.  The app I work on for work has many charts and graphs and includes several of these frameworks.

Following this feature, I think we should experiment with creating some React.js components for something small and simple.

I'd like to continue finishing this feature without the major backstep of ripping out D3.  This will allow us to easily include a horizontal bar chart in several places as shown in the wireframes.  

There is a separate discussion here about D3 being useful for understanding graphing fundamentals and why that is important in a chart-heavy app, but this pull request does not seem like a good place for that discussion.   Also I'm hoping that having such a discussion will not gate progress on this feature because I'd like to focus on finishing up the remaining work.  

I'm ready to continue with coding the few things left on this feature such as numbers showing the data and pulling in real data.  Perhaps I've written more than I needed to in this comment, but pull requests are so flat and I have no read on the depth of how much the choice of D3, a fundamental aspect of this work, is being questioned.  I do, however, assume that the question was raised because Growstuff has moved on from Tracker and it can be hard to get everyone on the same page when people are distributed around the world.  

I'm fine with adding comments at the top of the file and will work out how to get the data into the chart probably, as we discussed, with some kind of ruby method for getting the data together.

**Comment by tygriffin** [comment]
I didn't mean to give the impression that we should completely re-think the spec for this story and start from scratch! This PR addresses the task exactly as far as the original requirement is concerned (and you're right to re-emphasize it). Let's definitely *not* rip out d3.

You're also right that we should discuss future requirements for Growstuff charts elsewhere (like [Talk](http://talk.growstuff.org)) instead of blocking this PR.

As for ReactJS, I don't think it's at all incompatible with what you've written. My idea was that a React component would simply take in inputs and just forward them on to your code. Even if it didn't add any additional functionality, wrapping everything in React components would keep our JS component API's consistent.

**Comment by Marlena** [comment]
@tygriffin Thanks for your supportive comment.  That clears up so much confusion on my end.  Pull requests, what can I say?

Your idea of using a react component is interesting and worth a try.

**Comment by Marlena** [comment]
@tygriffin Also, I'd like to apologize for any part of miscommunicating that was mine.  I can see where I could have asked for a clarification of what you were saying and I'll plan to do that next time.

**Comment by tygriffin** [comment]
Nothing at all to apologize for!

iPhone$B$+$iAw?.(B

2015/02/16 1:31$B!"(BMarlena Compton <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by cesy** [comment]
What are the next steps in this? @Marlena, are you still working on it?

**Comment by Marlena** [comment]
@cesy Thanks for checking in.  The graphing bit is finished.  What's left
is connecting it with real data and writing some type of feature test.
I've arranged a local pair for this weekend to work on finishing this up.
Thanks for your patience.

**Comment by maco** [comment]
Because I have to be *that person*... do we know how this comes across for users of screen readers? Is the raw data spoken out loud? (ex: "sun thirty five part sun forty part shade twenty shade five")

**Comment by cesy** [comment]
Hi @Marlena, we're still keen for this if you're up for updating it.

**Comment by Marlena** [comment]
Thanks for checking in.

I am off for 2 weeks and can do some more work on it.

**Comment by cesy** [comment]
I would love to get this to a stage where we can merge the MVP, as this is a key feature for Growstuff to start making use of our data. I'm happy to spin off a separate issue to make it work for screen readers - that's important, but I don't want it to block getting this moving. I think Empty is useful data and can stay there, and we can spin off separate issues for total numbers and styling.

So things that are needed are sorting out merge conflicts, pulling real data, and adding a few more comments (doesn't need to be perfect, just a couple of hints, and we can improve it later). And merge conflicts are the least important of those, as one of us can do that part if needed. I see you've got notes in your Tracker for more tests, but I'm happy to defer those to a separate issue as well to get this moving again.

**Comment by cesy** [comment]
Are you interested in looking at this again? We've finally got things moving and are deploying new features to production regularly again.

**Comment by CloCkWeRX** [comment]
Replaced with #1121

**Pull request closed without merging**
