### PR TITLE
[WIP] bar graphs

### PR DESCRIPTION
**Pull request by pozorvlak**
I also think #688 is awesome, so here it is with the codeclimate problems fixed, hopefully. Currently mostly untested.

**Edit**: OK, I've now done some very preliminary testing, and there are two problems with this that I can see.

1. I can't work out how to run the JS unit tests. I'd been thinking of rebasing #1133 on top of this and using `jasmine` rather than `jasmine-rails`, but the [test-running instructions for Jasmine](https://github.com/jasmine/jasmine-gem/blob/master/README.markdown) aren't working for me on this code, so maybe it should be the other way round.
2. The actual data appears to be hardcoded (see screenshot). We should fix that before merging and deploying this :-) **Edit** - fixed in 7fa0d22.

screenshot from 2017-01-05 11-08-55

### CODE REVIEW

**Comment by pozorvlak** [comment]
Huzzah!

screenshot from 2017-01-09 15-13-41

Code rather horrible and inefficient, though - see  7fa0d22.

**Comment by cesy** [comment]
Looking exciting, but needs a rebase/dev merge before it can go in, from the look of things.

**Comment by Br3nda** [comment]
This looks mergable. Is it still WIP?

**Comment by CloCkWeRX** [comment]
I think there was "hook it up to real data" remaining.

**Comment by pozorvlak** [comment]
I've hooked it up to real data, albeit in a horrible and inefficient way. I wanted to write more unit tests, but I can do that in a later PR if you're OK with merging this as-is.

**Comment by CloCkWeRX** [comment]
Then lets merge I reckon!
(after tests pass)

**Pull request merged**
