### PR TITLE
Test creation of screenshots on Travis - DO NOT MERGE!

### PR DESCRIPTION
**Pull request by pozorvlak**
Adds a failing test to #924, so we can find out what happens when we try to create a screenshot on Travis.

### CODE REVIEW

**Comment by pozorvlak** [comment]
Huh, apparently .gitignoring database.yml doesn't actually stop Git from picking up changes to it. Curses!

**Comment by pozorvlak** [comment]
It would be nice to know why [a *different* page](https://travis-ci.org/Growstuff/growstuff/jobs/133361324#L1056) is being output by RSpec (it doesn't happen locally), but I think this experiment has been successful.

**Comment by maco** [comment]
I was noticing that and going "shit, did I leave a `puts page.body` in
after some debugging I was doing?"

**Comment by pozorvlak** [comment]
I looked through all the tests that visit `gardens_path` and couldn't find
one. Computers, eh?

**Pull request closed without merging**
