### PR TITLE
issue #1006: change "Freenode" to "irc.freenode.net" in README.md

### PR DESCRIPTION
**Pull request by ctlewitt**
Changed reference to "Freenode" to "irc.freenode.net" in README.md for clarification for newcomers to IRC.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
WE HAVE A FREENODE CHANNEL!?!!?!?!

More seriously, want to make that a link ( irc://irc.freenode.net/growstuff ) or something similar as well; so it's even easier?

**Comment by pozorvlak** [comment]
@CloCkWeRX we didn't tell you about it? \*smacks forehead\* We thought you knew about it but didn't use IRC...

@ctlewitt Good catch, but as @CloCkWeRX says a link would be even better. And please add yourself to CONTRIBUTORS.md!

**Comment by cesy** [comment]
Adding cross-reference in the comments because for some reason Github doesn't pick it up from the subject of a pull request, only the description or comments: #1006.

**Comment by ctlewitt** [comment]
Okay, so I'm super new to IRC.  Do most people use a web browser to view IRC?  Like this:
https://webchat.freenode.net/
(The link above didn't work for me, so I ended up with a Google search that took me there.  Does  irc://irc.freenode.net/growstuff or something related work for you?)  

Otherwise, I found downloading an IRC client and then going to channel #growstuff on the irc.freenode.net network helpful.  

I think the former has a lower barrier to entry, but  neither seems to give me any history if I log off and then log on again later.

**Comment by cesy** [comment]
People vary - some use a web browser, many use a client of some sort. For history, some people leave a client running all the time, or do something like screen+irssi, others have a bot that logs channel history somewhere. The web link has the lowest barrier to entry, as you say, and Gitter is also a low barrier to entry for people who aren't used to IRC.

**Comment by maco** [comment]
If you're running a Linux desktop, the irc:// type link will probably
launch the default IRC client. On Windows and Mac, though, IRC clients
aren't part of a default install and so much less commonly used, that the
browsers don't have irc:// handlers configured by default. The https://
link is better since it'll work for anyone who doesn't have an IRC client
set up yet.

**Comment by cesy** [comment]
Build failed with localhost intermittent issue, so restarted it.

**Pull request merged**
