### PR TITLE
Release 30

### PR DESCRIPTION
**Pull request by Br3nda**
toru tekau!

### CODE REVIEW

**Comment by Br3nda** [comment]
Resolved the git conflict with master. Anyone know why that happened?

**Comment by cesy** [comment]
Not sure - we've had a couple of mishaps in the past, but I thought they'd all long since been cleaned up.

Any idea why Travis is failing on an issue in account types here? It would be lovely to get some of this out quickly now we've got deployment working again, and get ourselves up to Rails 5 and some more of the new features Brenda's been doing.

**Comment by Br3nda** [comment]
I restarted the job, and it's passing now. Might be because >1 deploy was in flight? We should fix that.

**Comment by Br3nda** [comment]
I'm super keen to get those progress bars on my growstuff production data. Anyone happy to approve this release to prod?

**Pull request merged**
