### PR TITLE
Rubocop upgrade (and some style fixes)

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by oshiho3** [comment]
Hi @Br3nda,
I'm really sorry but I'm no longer available for reviewing.

**Comment by Br3nda** [comment]
OK @oshiho3. Github suggested you and do I went with it.

**Comment by Br3nda** [comment]
@oshiho3 how about we remove you as a code owner on growstuff

**Comment by oshiho3** [comment]
Yes, please. Thanks!

2017年12月4日(月) 14:29 Shiny <notifications@github.com>:

**Comment by Br3nda** [comment]
```
/home/travis/build/Growstuff/growstuff/.rubocop.yml: Style/MultilineMethodCallIndentation has the wrong namespace - should be Layout
/home/travis/build/Growstuff/growstuff/.rubocop.yml: Style/AlignParameters has the wrong namespace - should be Layout
/home/travis/build/Growstuff/growstuff/.rubocop_todo.yml: Style/BlockEndNewline has the wrong namespace - should be Layout
```

**Comment by Br3nda** [comment]
there were some new rubocop autocorrects, so i ran some of them, and reduced the .rubocop_todo.yml

**Comment by Br3nda** [comment]
Anyone around to review this?

**Pull request merged**
