### PR TITLE
update wiki links

### PR DESCRIPTION
**Pull request by maco**

### CODE REVIEW

**Comment by pozorvlak** [comment]
@homu-gs r+

**Comment by homu-gs** [comment]
:pushpin: Commit 745d83f has been approved by `pozorvlak`

**Comment by homu-gs** [comment]
:hourglass: Testing commit 745d83f with merge 49ff9d2...

**Comment by homu-gs** [comment]
:umbrella: The latest upstream changes (presumably #1007) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by CloCkWeRX** [comment]
I just applied this manually, tweaked wording a bit more. Still 1x wiki link (API) to clean up.

**Pull request closed without merging**
