### PR TITLE
Bundle Update on 2017-03-03

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), [6.7.5...6.7.6](https://github.com/ai/autoprefixer-rails/compare/6.7.5...6.7.6) ([CHANGELOG](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md))
- Updated: [js-routes](http://github.com/railsware/js-routes), [1.3.2...1.3.3](https://github.com/railsware/js-routes/compare/v1.3.2...v1.3.3) ([CHANGELOG](https://github.com/railsware/js-routes/blob/master/CHANGELOG.md))
- Updated: [selenium-webdriver](https://github.com/seleniumhq/selenium), [3.2.1...3.2.2](https://github.com/seleniumhq/selenium/compare/selenium-3.2.1...selenium-3.2.2)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
5 Pull Requests sent and 15 minutes, and 35 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
I'm happy to ignore the bundler-audit warnings, its not recognizing that 4.2.8 > 4.2.5.1

**Comment by CloCkWeRX** [comment]
Ugh, can't override the merge protection anymore, will leave for someone else

**Comment by Br3nda** [comment]
The bundle audit is just a warning. It's failing because depbot is not I'm contributors.md

**Comment by Br3nda** [comment]
I no longer have admin either. Can't override. Can't change settings.

**Comment by pozorvlak** [comment]
@CloCkWeRX, @Br3nda: dammit! Should be fixed now: try again?

**Comment by pozorvlak** [comment]
The "deppbot can't get past CI" issue should be fixed by #1262. I suggest merging that and then re-running static checks on this PR.

**Pull request merged**
