### PR TITLE
Upgrade rails, other gems

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Another version of #1237 - chipping away again at stale deps.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Not sure if 

1) Crop csv loading alternate names doesn't add a duplicate alternate name
     Failure/Error: expect(tomato.alternate_names.size).to eq 1
     
       expected: 1
            got: 0
     
       (compared using ==)
     # ./spec/models/crop_spec.rb:505:in `block (4 levels) in <top (required)>'

is flakey or legit regression.

**Comment by CloCkWeRX** [comment]
Maybe more alarming is the fact that exited with a 0/'tests passed'!

**Comment by CloCkWeRX** [comment]
Uh, hold off on merging this; its passing incorrectly (#1240). I'm not sure if the test was failing at the start.

**Comment by pozorvlak** [comment]
@mention-bot tags in a lot of people who are no longer active on the project: we should configure it not to, or revoke their commit access.

**Comment by cesy** [comment]
Let's remove commit access for the people who haven't been active in a long time.

**Comment by pozorvlak** [comment]
So that would be @tygriffin and @leto at least. @jcaudle recently mentioned
on IRC that he might have time to get involved again.

**Pull request merged**
