### PR TITLE
Fix #632 Make mailchimp newsletter subscription work again

### LINKED ISSUE #632: Newsletter subscriptions broken
Something seems broken on production, where new signups aren't getting added to Mailchimp.

http://growstuff.org/admin/newsletter shows me ~800 newsletter subscribers, but Mailchimp only shows me 500-ish total, with the numbers flattening off around March last year (eep!)

Workaround: before sending a newsletter, use the list at the link above and import it to Mailchimp manually.

To actually fix: need to dig around with the mailchimp API settings, I think :-/  Will probably need quite a bit of manual testing. Ugh.

### PR DESCRIPTION
**Pull request by twconquest**
Fix #632 . Change app/models/member.rb line 241 to point to correct mailchimp list.

Also, make changes to upgrade to [latest Gibbon v2.x](https://github.com/amro/gibbon).

Currently in process of testing. Not ready for merge just yet.

### CODE REVIEW

**Comment by twconquest** [comment]
We ( @pozorvlak and myself ) think the code is correct, but we have not managed to do any manual testing of it yet. As far as we know there are no automated tests setup for gibbon. Will revisit this next pairing session. Any suggestions for tests / best way to reliably automate tests for gibbon/mailchimp would be welcome.

**Comment by cesy** [comment]
The closest I could find to help was http://iswwwup.com/t/b98579e9ceb3/stubs-mailchimp-api-call-for-functional-testing.html, but there's a part of me that thinks automated tests are less critical for gibbon, as it's a low regression risk, and the critical parts are all in the config that won't get caught with automated tests anyway. So for the amount of effort, the chances of an automated test catching a bug are pretty low.

**Comment by pozorvlak** [comment]
We couldn't get this working with Gibbon 2.0, so we rolled back to v1.2 and applied the configuration fix. I've done the following manual tests locally:

 - create a new user, and check in the Mailchimp admin panel that they're subscribed to the mailing list;
 - click "unsubscribe" and "save" in an existing user's profile page, and check that they disappear in Mailchimp;
 - click "subscribe" and "save", and check that they reappear in Mailchimp.

**Comment by cesy** [comment]
Do we need to do anything special to set that config value in Production?

**Comment by pozorvlak** [comment]
It should already be set - run `heroku config --app=growstuff-prod` to find
out. I'm away from a computer for the next few days, so can't check myself.

**Comment by cesy** [comment]
Okay, looks good, happy to merge once conflicts are fixed.

**Pull request closed without merging**
