### PR TITLE
Auto corrected by following Style/OrAssignment

### PR DESCRIPTION
**Pull request by Br3nda**
Auto corrected by following Style/OrAssignment

Click [here](https://awesomecode.io/projects/55/ruby_configs/14312) to configure it on awesomecode.io

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Is dev itself unstable or something odd; its really weird this broke on update

**Comment by pozorvlak** [comment]
```
Failures:
  1) Planting a crop Marking a garden as inactive
     Failure/Error: click_link "Mark as inactive"
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
       ReferenceError: Can't find variable: gvjs_dA
       ReferenceError: Can't find variable: gvjs_dA
           at https://www.gstatic.com/charts/45.2/js/jsapi_compiled_fw_module.js:1 in global code
       ReferenceError: Can't find variable: gvjs_nv
       ReferenceError: Can't find variable: gvjs_nv
           at https://www.gstatic.com/charts/45.2/js/jsapi_compiled_timeline_module.js:30 in global code
     # ./spec/features/gardens_spec.rb:25:in `block (2 levels) in <top (required)>'
```

Bah. Re-running.

**Comment by pozorvlak** [comment]
This is now failing consistently on `dev` :-( Something to do with the change of charting library?

**Comment by Br3nda** [comment]
yes. for the timeline it pulls in the google charts from google's CDN... and it's broken :-(
Looking for a better way

**Pull request merged**
