### PR TITLE
Plantings form - photos/images selectors

### PR DESCRIPTION
**Pull request by Br3nda**
I'd like to make the plantings form a whole lot less daunting. This is a small step there. 
By using the names+photos of the gardens, the user can work out which garden they want to create the planting in much faster. It's one click, and it's visual now.

css needs some work, and the specs needs updating.

To make a planting, all that's needed is the crop and the garden. The form could make that clearer, to make entering data much faster for users.

### CODE REVIEW

**Comment by Br3nda** [comment]
image

**Comment by Br3nda** [comment]
Perhaps they can plant multiple crops in the garden at once...

**Comment by cesy** [comment]
Travis is failing and it's out of date - can you check, please?

**Comment by cesy** [comment]
I like the idea of this change, though.

**Comment by Br3nda** [comment]
@cesy I was waiting on feedback before fixing tests
I can make the CSS look better and update specs then...

**Comment by Br3nda** [comment]
Other idea if a "quick plant" form, from the Gardens#show page -- where you only need to select the crop and it creates a planting in that garden on that day (and take the suniness etc from the other plantings)

**Pull request closed without merging**
