### PR TITLE
Routes tidy up

### PR DESCRIPTION
**Pull request by Br3nda**
- [x] simplified routes.rb to be more standard rails resources, less special routes
- [x] Update member URLs to always use `slug` and not `login_name`
- [x] Moved gardens_by_owner, plantings_by_owner, harvests_by_owner, and seeds_by_owner to be nested under members instead
  - members/:slug/gardens
  - members/:slug/plantings
  - members/:slug/harvests
  - members/:slug/seeds
- [x] Added new routes members's posts (the old posts by author route stays, so permalinks to existing posts still work)
  - members/:slug/posts
- [x] Crop is looked up by `slug`, so call the variable slug instead of id
- [x] Members are looked up by `slug`, so call the variable slug instead of id
- [x] Added `crops/:slug/plantings`,`crops/:slug/harvests`,`crops/:slug/seeds`
- [x] Use member.to_param and crop.to_param to make unique id in filenames etc.
- [x] Use the same nav button structure/template on gardens/plantings/harvests/seeds (DRYer)
- [x] Other small code DRYing noticed while there.

Rails can work out what we mean now,
 so `gardens_by_owner_path(owner: @owner)` becomes just `member_gardens_path(@owner)`
`posts_by_author_path(author: current_member.slug)` becomes `member_posts_path(current_member)`

### CODE REVIEW

**Comment by Br3nda** [comment]
Let's get the Rails 5 live before this - because it's quite big

**Comment by Br3nda** [comment]
(rebased this branch)

**Comment by Br3nda** [comment]
I think this needs merging next, so we don't cause masses of git conflicts.

**Comment by pozorvlak** [comment]
Wait, actually, no: I get (simple-looking) conflicts if I try to rebase it onto dev, and it's failing CI anyway:

```
January 24, 2019 at 03:21: Rack app error handling request { GET /seeds/new }
#<ActionView::Template::Error: undefined method `gardens_by_owner_path' for #<#<Class:0x000000000b614558>:0x000000000b6e6120>
Did you mean?  gardens_path>
/home/travis/build/Growstuff/growstuff/app/views/shared/_global_actions.html.haml:4:in `_app_views_shared__global_actions_html_haml___3978820560919731782_92386920'
```
plus lots of similar errors. Also, our Travis logs are now full of stack traces so I can't see the full list of failing tests :-(

@Br3nda, can you please rebase this onto dev and fix the test failures?

**Comment by Br3nda** [comment]
The recent merge of dev branch into here has made some regressions (some new code will have the old route names)
I'll fix up shortly.

**Pull request merged**
