### PR TITLE
Add a location not set layout (lets try this again!)

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Based on MIT licenced icon-globe (http://fontawesome.io/3.2.1/icon/globe/)

Addresses #913

image

Probably could be done without the wording stuck into the image itself, but this seemed a lot easier to achieve

### CODE REVIEW

**Comment by maco** [comment]
Can you add screenreader helper text? Bootstrap [has a class for that](http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_hlp_sr-only&stacked=h)

**Comment by CloCkWeRX** [comment]
Sorted

**Comment by pozorvlak** [comment]
Looks sensible - do we also need to set an alt-text on the image?

Nitpick: best practice for long commit messages is to have a <50-character summary line (which can be read easily in pull request summaries, `git-log` output, etc), and put more details in subsequent paragraphs. I'd have written the message for your first commit as

```
Add globe icon for "location not set"

Based on MIT-licenced icon-globe:
http://fontawesome.io/3.2.1/icon/globe/
```

**Comment by maco** [comment]
The image is a background image on a div, not an img tag. Consequently,
there's nothing to put an alt tag on, which is why I had him add the
screenreader-only text.

**Comment by pozorvlak** [comment]
Brilliant, thanks for the explanation!

**Pull request merged**
