### PR TITLE
Issue 565 create harvests RSS

### PR DESCRIPTION
**Pull request by robotscissors**
This should solve issue #565.

Your feedback is welcome. 

Files modified:
* __harvests_controller__ - so the controller can respond to rss requests.
* __view/harvests/index.html.haml__ - modified the links on this index page to access the RSS feeds (both for an individual owner or all members.
* __view/harvests/index.rss.haml__ - created this file to handle the RSS feed requests. I based it on the previous RSS feeds for plantings and seedings but changed it based on the db table harvests.
* __spec/views/harvests/index.rss.haml_spec.rb__ - created an rspec file to assist in testing which was based on the plantings rspec file.

I tested it on a browser feed-burner, and I did struggle with the tests. I know how important they are.

### CODE REVIEW

**Comment by Br3nda** [comment]
Looks good. Just one small fix needed to make the linter happy.

**Comment by robotscissors** [comment]
Hi, @Br3nda I need a little nudge. The first pass of Hound said  "Style/UnneededInterpolation: Prefer to_s over string interpolation." so I added the .to_s to line 36 above. But now it is saying "Lint/StringConversionInInterpolation: Redundant use of Object#to_s in interpolation." 

I am not sure which way to turn :)

**Comment by Br3nda** [comment]
try this one
`rendered.should have_content @tomato.name`


but also, the `should` syntax i think is getting deprecated soon, so you could also upgrade it to the new expect syntax:
`expect(rendered).to have_content @tomato.name`

**Comment by Br3nda** [comment]
It just needs one more thing.

>Thanks for your contribution, robotscissors!
>Please add your name and GitHub handle to the file CONTRIBUTORS.md,
commit it, and update your PR.

**Pull request merged**
