### PR TITLE
 Clip long text in definition lists within panels

### LINKED ISSUE #856: Garden card UI needs to apply overflow:hidden more strictly
image

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #856

### CODE REVIEW

**Comment by pozorvlak** [comment]
Despite this PR passing CI, the automated build of `dev` failed. See #901.

**Comment by maco** [comment]
One I merged last night also passed tests in PR and failed that way later.

**Comment by pozorvlak** [comment]
OK, perhaps it's a difference in configuration between the dev builds and
the PR builds?

**Comment by maco** [comment]
Don't know. It passed on re-run I think? I've also seen it on a local run.

**Comment by pozorvlak** [comment]
OK, probably not a configuration difference, then. Oh dear.

**Comment by maco** [comment]
Race condition? (I really don't like race conditions...)

**Comment by pozorvlak** [comment]
Between the test code and the creation of the ElasticSearch index? Yeah, that sounds plausible. I guess the way to check would be to add a delay into the index creation, or run that test hundreds of times in a loop.

**Pull request merged**
