### PR TITLE
Fix up of photo display on garden#show

### PR DESCRIPTION
**Pull request by Br3nda**
fixes: #1330

before:
image

image

after
image

image

### CODE REVIEW

**Comment by cesy** [comment]
I'm not sure I like the photos going so much smaller on mobile - can we adjust the responsive settings to make it 2 or 3 columns rather than 4 at that size, please?

**Comment by Br3nda** [comment]
I fixed up the alignment of the labels+buttons too:
image
image

**Comment by Br3nda** [comment]
I think it needs more changes -- when you're trying to find "what is planted here, when will it be ready for harvest" the photos get in the way. They're all the photos ever of that garden, which may have been tracked for years.

**Comment by Br3nda** [comment]
image

image

**Comment by Br3nda** [comment]
There's still lots of grey unused space, and the plantings fall below the fold

**Comment by Br3nda** [comment]
image

**Comment by Br3nda** [comment]
i think this looks better - photos moved to right/bottom

image
image
image
image
image

**Comment by Br3nda** [comment]
trying another way. This shows the first 5 photos of a garden (in the original location on the page) and then a link to see the rest via the photos_controller

image
image

**Comment by Br3nda** [comment]
I think the purpose of seeing finished plantings is crop rotation (recently finished and last year) and knowing what grew well more than a year ago... 
Perhaps we can show that clearer instead of listing all plantings ever in the garden.

**Comment by Br3nda** [comment]
I'd love a code review here -- so i can send through more PRs to fix up other display UX things

**Comment by CloCkWeRX** [comment]
I think this is enough to fix #809 as well

**Pull request merged**
