### PR TITLE
Check we have a planted_at ts before using

### PR DESCRIPTION
**Pull request by Br3nda**
fix for #1079
Check we have a planted_at ts before doing maths with it

### CODE REVIEW

**Comment by maco** [comment]
Looks good, but I'm not sure how to make a hotfix such that I don't mess up Git. I never did the button pushing part before. I *think* the answer is:

1. merge this into *master*
2. @pozorvlak 's recent change for production pushes should make that automatically go live
3. merge from master back into dev so that we don't get conflicts on next dev -> master release

Does that sound right? Possibly merging into dev and using cherry picking magic in git is also an answer... @CloCkWeRX ?

**Comment by pozorvlak** [comment]
@maco: yes, that's exactly right (and should be simpler than
cherry-picking). I'm +1 to this, but don't have a computer handy: please
merge it.

**Comment by maco** [comment]
@Br3nda can you rebase onto master, so I can merge it there?

**Comment by maco** [comment]
('cuz this is done from dev and so has all the other stuff that's been merged)

**Comment by Br3nda** [comment]
@maco now rebased from master

**Comment by cesy** [comment]
Okay, doing the merge from master back to dev now.

**Comment by pozorvlak** [comment]
The build of master failed, so the autodeploy didn't happen. I've restarted it.

We *really* need to fix our flaky-CI problem.

**Comment by cesy** [comment]
Okay, I've done a manual deploy from Heroku so it's live, then let's just get the whole of Release 16 live later today and get it all properly there.

**Comment by pozorvlak** [comment]
"Skipping a deployment with the heroku provider because this branch is not permitted" - because the changes to .travis.yml haven't been merged to master yet :-(

**Pull request merged**
