### PR TITLE
upgrade leaflet-rails

### LINKED ISSUE #1211: Upgrade to leaflet-rails 1.0.0+
#1204 #1209 followup - a bunch of tests fail at the moment, haven't investigated much into why

### PR DESCRIPTION
**Pull request by Br3nda**
fixes #1211

### CODE REVIEW

**Comment by cesy** [comment]
Thank you so much for tackling this.

**Comment by Br3nda** [comment]
curiously the specs passed on my laptop. 
Not sure what's different on travis yet.

**Comment by CloCkWeRX** [comment]
Past me is entirely unhelpful here:
```
gem 'leaflet-rails', '~> 0.7.7'    # Newer versions break tests - see https://travis-ci.org/CloCkWeRX/growstuff/builds/200984350
```

**Comment by CloCkWeRX** [comment]
Unhelpfully, leaflet-rails is synced to the js library version number.

https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#100-2016-09-26 - quite a few changes since 0.7.7

Worth checking all of the 'API changes' against our code...

**Comment by Br3nda** [comment]
@CloCkWeRX do you recall all the things leaflet is doing for us in growstuff?

**Comment by Br3nda** [comment]
looks like leaflet-markercluster-rails throws errors on the latest leaflet. I can get it working by turning off clustering.

**Comment by Br3nda** [comment]
nvm - looks like the gem moved from rubygems to rails-assets.org
sorted.

**Comment by Br3nda** [comment]
image

**Comment by Br3nda** [comment]
Summary of changes:
Upgraded leaflet. 
Changed source of leaflet cluster markers gem
Also fixed our phantomjs install and usage in test runs.

**Pull request merged**
