### PR TITLE
Show user role (admin/wrangler) in profile page

### PR DESCRIPTION
**Pull request by jacemonje**
To answer https://github.com/Growstuff/growstuff/issues/557

### CODE REVIEW

**Comment by jacemonje** [comment]
@pozorvlak

**Comment by pozorvlak** [comment]
The basic idea's right, but there are a few problems here:

 - Commit 6d2edf8 has been included, but it's not related to this issue. An equivalent commit with a different ID has been merged - I'm guessing this was left over from a rebase.
 - There's now a merge conflict with the current dev branch - can you please merge or rebase and fix the conflicts? If you rebase you can eliminate 6d2edf8 while you're at it :-) Please let me know if you need some help with this.
 - You've committed commented-out code: either delete the code if it's no longer needed, or fix it. In this case, it looks like it is needed - can you run the tests and post the error message if the test concerned still fails?
 - The issue description asks for crop wranglers to be shown; you've only shown admins.
 - Please add feature tests to check that admins and crop wranglers have the new information shown on their profile pages!

**Comment by jacemonje** [comment]
Hi! Noted; will fix this :) Thanks @pozorvlak!

**Comment by pozorvlak** [comment]
Great! Visual-design-wise, check out the discussion on #735.

**Comment by jacemonje** [comment]
I've badly muddled up this branch of mine. I'll just make a new PR with a new branch so it'll be cleaner and easier for everyone to view.

**Comment by jacemonje** [comment]
Closing this and made a new one here: https://github.com/Growstuff/growstuff/pull/767

I'm still confused with testing. Can a given member be ONLY either an Admin or Crop Wrangler?

**Comment by pozorvlak** [comment]
No, a given member can be an admin and a crop wrangler at the same time - there's a many-to-many relationship between Member and Role. See https://github.com/Growstuff/growstuff/blob/dev/app/models/role.rb#L5 for the relevant code.

**Pull request closed without merging**
