### PR TITLE
Fix mentionbot config

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by pozorvlak** [comment]
@Br3nda, would you mind splitting out the mentionbot config from the Ownable changes? I think it should be enough to rebase this branch onto #1605.

**Comment by Br3nda** [comment]
That's where it went! I lost those changes and retyped it.
I'll fix up and push here again soon.

**Comment by Br3nda** [comment]
@pozorvlak ready for review again

**Comment by Br3nda** [comment]
I've learned it's not a config problem. The bot is broken.

**Pull request closed without merging**
