### PR TITLE
Production push (release 8): request crops, search sci/alt names, garden photos, and more

### PR DESCRIPTION
**Pull request by maco**
**New Features**

- New crop request form! This makes the approval process easier on the crop wranglers.
- Search now checks alternate names (such as coriander and cilantro) and scientific names
- Seeds have organic, GMO, and heirloom options, along with and how many days until maturity
- You can now attach photos to your garden
- On the member page, members can be sorted by name or by how recently they joined
- When logged out, visitors will see a note at the top of post pages, so first-time visitors can see what Growstuff is all about
- Wranglers now see a "wrangle crops" button on the crop listing page

**Bug Fixes**

- You can no longer claim to have fewer than 0 seeds.
- The page footer height has been tweaked.
- You can no longer follow yourself.
- Crop wranglers will no longer see an error page if they leave out the Wikipedia link when adding a new crop.
- Some formatting bugs with the homepage and browse crops have been fixed.
- Sometimes users would see an error page when they tried to follow other users: this should no longer happen.
- Users should no longer receive an error when trying to download harvest data.
- Harvest photos should now provide a link back to their harvest after attaching the photo.

**Technical Improvements**

- Static content like the page footer is now stored in a CMS, for easier maintenance.
- We're now storing all harvest weights as kilograms in addition to whatever unit you put in, with conversion handled by ruby-units. This will let us give harvest totals more easily in the future.
- Users can now search by alternate names, scientific names, and partial names, with the matching handled by ElasticSearch.
- Travis CI now pushes successful builds on the dev branch to the staging site on Heroku, so merging a pull request to dev automatically deploys it to staging.
- Lots more features are now covered by automated tests.

### CODE REVIEW

**Comment by Skud** [comment]
Wheee! I will probably review this (mostly for the release notes) properly in the next day or so then do the production push but in the meantime it would be great if other people could go through the release notes and check whether there's anything missed, or that could be phrased better, or whatever.

One comment for @maco, I know I said to use end-user language throughout, but for the technical improvements we can actually say what the things are (eg. "Set up continuous integration through Travis-CI") as long as we also explain in slightly less technical terms ("... to automatically push changes to our staging site").

**Comment by maco** [comment]
@tygriffin @pozorvlak @cesy @oshiho3  any comments?

**Comment by pozorvlak** [comment]
Looks good!

**Comment by tygriffin** [comment]
Looks good to me, too! Great to see this!

**Comment by oshiho3** [comment]
Looks good. Thanks @maco!

**Comment by pozorvlak** [comment]
I've tweaked the wording on the release notes to make them less repetitive - though in the process I made them more verbose :-( @Skud, @maco, how do they look?

**Comment by Skud** [comment]
Sorry for taking soooooo long to get to this! @pozorvlak the release notes look great. Let's ship it!

**Comment by pozorvlak** [comment]
Pushed to production! [Growstuff Talk release thread](http://talk.growstuff.org/t/release-8-productionpush-2015-07-08-1600-utc/275/2).

**Pull request merged**
