### PR TITLE
Show edited date/time on posts/comments and Show last login date on member profile

### PR DESCRIPTION
**Pull request by CjayBillones**
@Skud  this PR is for issues #476 and #546 .

The system changes Posted by <name> on <date/time> into Edited by <name> on <date/time> whenever a post/comment is edited.

screen shot 2015-06-23 at 8 31 00 am

### CODE REVIEW

**Comment by CjayBillones** [comment]
@pozorvlak Hi! Would you like to also check this out? Thanks! :)

**Comment by pozorvlak** [comment]
The code changes look good, but there are a few things I'd prefer you to do before I merge this:

 - add some tests!
 - split out the change to `.gitignore` into its own commit, so it's more obvious why the change was made
 - either remove the changes to `Gemfile` and `Gemfile.lock`, or split them out into a separate commit explaining why they were made. You just added a library to support history-editing in interactive sessions, right?

Do you need any help to do those things, or are you confident to go ahead on your own?

**Comment by CjayBillones** [comment]
Hi @pozorvlak , I've already made the things that you have requested.

- I added the necessary tests
- split out the change in gitignore
- removed the changes to Gemfile and Gemfile.lock

Will you check it out? And also, I already added myself in the list of contributors. Thanks!

**Comment by pozorvlak** [comment]
Excellent, thanks! There's a slight wording change needed (which I should have picked up on before, sorry!) and it would be great if you could rebase against the current dev branch.

**Comment by CjayBillones** [comment]
@pozorvlak it's done! :)

**Comment by CjayBillones** [comment]
@pozorvlak seems like you missed this earlier. :) I've finished it already. :D

**Comment by CjayBillones** [comment]
Hi @maco and @pozorvlak . Is this already fine?

**Comment by pozorvlak** [comment]
Looks good! Sorry for my non-responsiveness - I was travelling to, attending, and then returning from a friend's wedding in a remote and distant part of England, and didn't have much Internet access (or energy left over!).

**Comment by pozorvlak** [comment]
Have some [photos of the wedding](https://plus.google.com/collection/A1rdV) - I'm one of the people standing in the paddling pool, though you can't see my face :-)

**Comment by CjayBillones** [comment]
woah, cool. :)

**Pull request merged**
