### PR TITLE
Upgrade gibbon

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Minor version bump from the rails 4.2 upgrade work

### CODE REVIEW

**Comment by pozorvlak** [comment]
@homu-gs r+

**Comment by homu-gs** [comment]
:pushpin: Commit faa3bed has been approved by `pozorvlak`

**Comment by homu-gs** [comment]
:hourglass: Testing commit faa3bed with merge 8358700...

**Comment by CloCkWeRX** [comment]
Is homu-gs trying to integrate this into master, not dev?

**Comment by maco** [comment]
Good catch! It's not something that's in the config file, just hard-coded
>_> Code has been updated on my server.

**Comment by CloCkWeRX** [comment]
Merging due to "Commit faa3bed has been approved by pozorvlak", rather than waiting for homu to finish

**Pull request merged**
