### PR TITLE
[#568] Signout redirects to last page visited

### PR DESCRIPTION
**Pull request by jacarandang**
Sign out redirects to last page visited however, it doesn't redirect to root_path if the page last visited needs authentication (e.g. edit account), instead it is redirected to the login page

### CODE REVIEW

**Comment by jacarandang** [comment]
#568

**Comment by pozorvlak** [comment]
Looks good, but can you please add a feature test for this? See the `spec/features` directory for some examples.

**Comment by jacarandang** [comment]
Added some test

**Comment by pozorvlak** [comment]
Thanks!

**Comment by CloCkWeRX** [comment]
This didn't seem to work on staging.

When signing out, you get redirected to the last page you were on, if it's something public, rather than always to the homepage
* Login
* Edit your profile
* Signout

Expected: redirect to /
Actual: prompted to login to access the member profile edit UI

**Pull request merged**
