### PR TITLE
Remove vendor directory

### PR DESCRIPTION
**Pull request by pozorvlak**
An alternative to #973.

### CODE REVIEW

**Comment by pozorvlak** [comment]
@maco: I think this is done now, is there anything else you'd like to see? We could possibly kill commit 936aa17 on the grounds that those lines aren't doing any harm and we may some day put something else in `vendor`, but on the other hand YAGNI.

**Comment by pozorvlak** [comment]
@maco: are you adding labels manually, or have you set up a bot to do that? I'm wondering if we should create a @growstuff_bots account for things like that.

**Comment by maco** [comment]
Editing the config file? Manually, but CC gives us patches to apply to
ignore specific issues.

**Comment by pozorvlak** [comment]
No, I meant the "in progress" label that appeared mere seconds after I
opened the PR :-)

**Comment by maco** [comment]
No, I was wondering about those too, but actually, I think it might be
waffle.io It puts things in categories like Pivotal does, and if you have
the bug number in your branch name it shows the issue as being worked on.

**Pull request merged**
