### PR TITLE
Issue #640 mincontainer

### PR DESCRIPTION
**Pull request by cesy**
Not ready to merge, needs testing, but leaving it here so others can find it easily (including me on the other computer)

### CODE REVIEW

**Comment by cesy** [comment]
Got it, from http://stackoverflow.com/questions/16642866/height-percentage-not-working-in-css. This now works without any complaints about invalid properties, but I can't figure out how to reproduce the original weirdness to ensure it's properly fixed.

**Comment by Skud** [comment]
The signin page (in a suitably large browser window) was a good example: 
http://growstuff.org/members/sign_in

On 20/01/2015 12:50 am, Cesy wrote:
>
> Got it, from 
> http://stackoverflow.com/questions/16642866/height-percentage-not-working-in-css. 
> This now works without any complaints about invalid properties, but I 
> can't figure out how to reproduce the original weirdness to ensure 
> it's properly fixed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/pull/655#issuecomment-70494502>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by cesy** [comment]
Got it. 90% was too tall on my screen, but 80% did the trick.

**Comment by pozorvlak** [comment]
I've merged but not deployed this: I'm kinda hoping someone will merge #659, which will deploy this automatically :-) Same goes for #647.

**Pull request merged**
