### PR TITLE
Handled Issue #950 (Branded Error Pages)

### PR DESCRIPTION
**Pull request by Prashanth261993**
Moved error related views from public to errors (asset pipeline can be used).
Header and footer were included along with the error message.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Ooops, a few merge conflicts - can you git pull to get the latest?

**Comment by Prashanth261993** [comment]
@CloCkWeRX  Pulled the growstuff-dev and merged with mine and resolved the conflict (CONTRIBUTORS.md). Will this do?

**Comment by pozorvlak** [comment]
Merging, but noting for future reference: we were expecting this issue to be fixed by adding to the static HTML pages in `public/`, rather than replacing them with HAML but, it [looks like it's impossible to use site styles in static pages under Rails 4](https://mattbrictson.com/dynamic-rails-error-pages). I don't know how much we should worry about the "I can't report errors, because [my error-reporter is broken](http://scholar.harvard.edu/files/mickens/files/thenightwatch.pdf)" scenario - @cesy?

**Comment by pozorvlak** [comment]
@Prashanth261993 congratulations on landing your first PR with us :-) I'd have used a summary message "Add branding to error pages (issue #950)" in line with [best practice](http://chris.beams.io/posts/git-commit/) (use the imperative, focus on what the change *does*), but that's a micro-nit.

**Comment by pozorvlak** [comment]
Actually, I'd probably have said "Add branding to error pages" and then put "Fixes #950" somewhere in the body of the commit message, but we're well into [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) at that point.

**Comment by pozorvlak** [comment]
I just checked `http://staging.growstuff.org/wilma` and saw a blank page instead of a 404 error page. So I'm afraid this needs more work - reverting for now.

**Pull request merged**
