### PR TITLE
Ban hammer

### LINKED ISSUE #2091: banhammer - easier way to ban/delete spammers and their data

### PR DESCRIPTION
**Pull request by Br3nda**
and easier way to ban the users that are posting spam
closes  #2091

### CODE REVIEW

**Comment by pozorvlak** [comment]
```
Failures:
  1) forums/show shows posts
     Failure/Error: rendered.should have_content @post.subject
       expected to find text "The Curious Incident of the Dog in the Night-Time" in "Permaculture This forum is run by OPEFXBNM Everything about permaculture! Posts Post something Subject Posted by Most recent activity Comments The Curious Incident of the Dog in... OSZWPFBV 16 Jul 0"
     # ./spec/views/forums/show.html.haml_spec.rb:34:in `block (2 levels) in <top (required)>'
  2) Members RSS feed The show action title is what we expect
     Failure/Error: - @posts.each do |post|
     
     ActionView::Template::Error:
       undefined method `each' for nil:NilClass
     # ./app/views/members/show.rss.haml:6:in `_app_views_members_show_rss_haml__4257156189909393344_103945740'
     # ./app/controllers/members_controller.rb:32:in `block (2 levels) in show'
     # ./app/controllers/members_controller.rb:28:in `show'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `each' for nil:NilClass
     #   ./app/views/members/show.rss.haml:6:in `_app_views_members_show_rss_haml__4257156189909393344_103945740'
```
I guess the long post title is being truncated?

Side-note: it would be really nice if the failing tests got reported back as a GitHub comment rather than me doing so manually. Is there a plugin to do this? I had a brief look, but couldn't find one.

**Comment by Br3nda** [comment]
@pozorvlak such a bot sounds useful. I've tried a couple times to migrate us to circle ci - where we can get more granular control of parallel tasks and dependencies between task. That would notify us on which task failed (e.g. the linter, or the elastic search rspec run).

**Comment by Br3nda** [comment]
Once this is live, we can go through the spammers reported here 
https://www.growstuff.org/posts/bigblen-20190709-forum-spam

**Comment by Br3nda** [comment]
05a1a8c83d7c2095b5073562dddb79b3278d078f1cfb288b205d01dac1602a2f

**Pull request merged**
