### PR TITLE
Release 38

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by Br3nda** [comment]
there's an error on staging "Error Loading Chart: Unauthorized" on the new chart api methods. Looks like they don't work in you're not logged in.

**Comment by Br3nda** [comment]
chart permissions error on staging is fixed in #1527

**Comment by Br3nda** [comment]
Re ran the tests and they are green again.

**Comment by Br3nda** [comment]
Release blocked by #1536

**Comment by Br3nda** [comment]
Just needs #1540 to fix the permissions error on pie charts. Then a test then we're good to go.

**Comment by Br3nda** [comment]
I HAVE RELEASED THE KRAKKEN.... or the graphs. or both.

**Comment by pozorvlak** [comment]
Muahahahahaha!

**Comment by CloCkWeRX** [comment]
we are doing evil villian laughing? Better get on board

MUAHAHAHAHa-cough splutter-ha

On 23 Jan. 2018 9:20 pm, "pozorvlak" <notifications@github.com> wrote:

Muahahahahaha!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Growstuff/growstuff/pull/1516#issuecomment-359752986>,
or mute the thread

**Pull request merged**
