### PR TITLE
Release 13

### PR DESCRIPTION
**Pull request by CloCkWeRX**
We should probably put this out even if it means bumping a lot of stuff from the roadmap.

### CODE REVIEW

**Comment by pozorvlak** [comment]
Agreed, let's get a release out soon even if it doesn't include all the stuff we'd like. @Cesy, @maco?

**Comment by pozorvlak** [comment]
Build failed with an "ElasticSearch::ServiceUnavailable" error; re-running.

**Comment by cesy** [comment]
Yes, agreed.

**Comment by pozorvlak** [comment]
I'm away camping this weekend and likely to have limited Internet access; I
won't be able to help with the deploy until Monday, but feel free to
proceed without me :-)

**Comment by CloCkWeRX** [comment]
Staging looks briefly ok, though I only clicked around a little given how little user facing changes are in here...

**Pull request merged**
