### PR TITLE
iCalendar feed of plantings

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Partially improve #1447
Partially solve #472
Partially solve #2082

Another one for squash merging

image

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
image
Okay, pretty happy with that. Staging doesn't have predictions, but should work out okay

**Comment by CloCkWeRX** [comment]
On mobile:
Screenshot_20240121-183436
Screenshot_20240121-183430

**Comment by cesy** [comment]
Security-wise, it looks like you only provide the link to the owner, but anyone can access it - is that right, since it's not secret but it's most useful to the owner? Is it worth adding a test to make that behaviour clear, that you can access someone else's calendar if you want to help a friend or something, but the page isn't cluttered with a link unless it's your own?

**Comment by cesy** [comment]
Otherwise it seems good to me on a quick skim.

**Comment by CloCkWeRX** [comment]
I'll have a think about it. The intent was to make multiple feeds, tied to a person and also not, like the RSS feeds, JSON feeds, etc long term.

**Comment by CloCkWeRX** [comment]
For now, going to merge as is.

**Pull request merged**
