### PR TITLE
Badges for ready to harvest, days to finished

### LINKED ISSUE #1469: If no prediction data available for a crop, use that from the parent
We don't have data for every tomato variety, but we have good tomato data. Explore ways to use this to give more predictions

### LINKED ISSUE #1538: Tell me what will be ready to harvest soon?
Help me predict what will likely be ready to harvest now, next week, next month.

### PR DESCRIPTION
**Pull request by Br3nda**
I'm going to add colours and specs..
but here's this morning's work adding some badges to the planting thumbnails to indicate harvest readiness and time to finished

image

TODO:
- [x] Specs
- [x] i18n
- [x] colours
- [x] colourblind acessible
- [x] screen reader check)

closes #1538
closes #1469

### CODE REVIEW

**Comment by Br3nda** [comment]
Tidying up the visual link form the photos to the crop name
image

**Comment by Br3nda** [comment]
Colours. Used red for zombies, and blue for ready to harvest.
also added a button to mark planting finished if it's a zombie.

Zombie means it's lived a long way past when the finish was predicted.


image
image
image
image

**Comment by Br3nda** [comment]
I think this is done now.

**Comment by Br3nda** [comment]
Also closes #1469

**Comment by jenkr55** [comment]
I don't think "zombie" has an intuitive meaning, is there somehow we can clarify that to the end users? Unless it's an actual gardening term I haven't heard of

**Comment by CloCkWeRX** [comment]
"Mature"? "Self propagating"?

**Comment by jenkr55** [comment]
I'm good with either of those^, or maybe "late" or something? I'm not sure if there's a term for it

**Comment by Br3nda** [comment]
Its for those 5 year old tomato plants that for sure arent actually still alive in gardens.

**Comment by Br3nda** [comment]
how about `super_late?` ?

**Comment by jenkr55** [comment]
“Zombie” makes sense now, I’m good with either!

**Comment by jenkr55** [comment]
That works too!

**Comment by Br3nda** [comment]
also renamed `should_be_finished?` to `late?`

so we have 'late?` and `super_late?`

image

**Comment by Br3nda** [comment]
I'd love to merge this. Any more feedback on it?

**Comment by jenkr55** [comment]
I didn't have any more feedback from my first look at it. I've got a busy
week this week and probably won't be able to contribute a whole lot until
the weekend again

**Comment by Br3nda** [comment]
All good. It's public holiday here, but my brain thought it was the weekend.

**Pull request merged**
