### PR TITLE
#910: Crop approval flash alert for wranglers upon sign in

### PR DESCRIPTION
**Pull request by Thrillberg**
Issue 910.

This is my first non-trivial (ie, grammar) open source contribution. Did I do it right? What can I improve?

### CODE REVIEW

**Comment by maco** [comment]
Would you mind adding a feature test for this? We use Capybara to visit
pages and check that they have the messages we expect to see. They're in
spec/feature/

Thanks!

**Comment by maco** [comment]
(And thank you for making us your first substantial contribution to open
source!)

**Comment by Thrillberg** [comment]
Thanks! Just put a test up.

**Comment by pozorvlak** [comment]
Looks great! I can think of two small improvements you could have made:

1. It makes life slightly easier for reviewers if you make whitespace-only changes in a separate commit from substantial code changes.
2. The alert message is hardcoded; we're slowly moving all user-visible text to `config/locales/{en,jp}.yml` so the site can be displayed in multiple languages. But we'll have to do that in lots of other places too, and it'll probably be easier to do it in a batch later.

I don't think either of these issues blocks this being merged. Please add yourself to `CONTRIBUTORS.md` and we're good to go!

**Comment by Thrillberg** [comment]
Cool, thanks! I didn't know about the whitespace thing but it looks like Atom does that automatically--how annoying. I'm trying to figure out how to disable that feature.

**Pull request merged**
