### PR TITLE
Update entire project to ruby 2.0 hash syntax

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Result of:
```
$ rubocop --only HashSyntax --auto-correct

483 files inspected, 2018 offenses detected, 2018 offenses corrected
```

If this ends up with conflicts after other stuff is merged; easy enough to redo. Alternatively, its easy enough to do a section at a time - ie; all db migrations followed by all models; then controllers; specs... etc etc.

### CODE REVIEW

**Comment by cesy** [comment]
Let's do this once Release 9 is live. What other bits do we still need fixed for that?

**Comment by maco** [comment]
@CloCkWeRX

**Comment by maco** [comment]
(had to close & re-open to trigger Travis to use the new version of Ruby)

**Comment by maco** [comment]
Oh good, still green after the largish merges this morning.

**Pull request merged**
