### PR TITLE
Queue mail in sidekiq

### PR DESCRIPTION
**Pull request by CloCkWeRX**
#951

### CODE REVIEW

**Comment by cesy** [comment]
I'll wait for a second opinion from @maco on switching to sidekiq, but this looks good to me.

**Comment by maco** [comment]
I'm fine with the use of sidekiq in general (we use it at work), though I
have no particular expertise as to the configuration itself.

**Comment by homu-gs** [comment]
:umbrella: The latest upstream changes (presumably #1033) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by cesy** [comment]
Okay, so we're good to merge once the conflicts are fixed.

**Pull request merged**
