### PR TITLE
Improve the styling of a planting to be more like the other card-layouts

### LINKED ISSUE #870: New card UI - style regression for plantings
Not present/style regression for plantings: staging.growstuff.org/members/clockwerx or staging.growstuff.org/plantings/

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #870

Before:
http://growstuff.org/plantings/

After:
image

I haven't checked this on mobile yet, and the fixed-width behaviour I used to style the definition list feels wrong (on the other hand, the previous styling also used fixed widths)

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
I think that's everything now, though the plantings show UI probably needs redesign

**Comment by maco** [comment]
For mobile testing, did you know Chrome's "inspect element" has a mobile test mode? There's a dropdown for devices, and it'll jump to that resolution.

**Comment by CloCkWeRX** [comment]
Think this is ready when tests pass now

**Comment by pozorvlak** [comment]
Looks good to me! One tiny nitpick: it's good to keep commit summaries within 50 characters, and put extra information in subsequent paragraphs.

**Pull request merged**
