### PR TITLE
Release 19

### PR DESCRIPTION
**Pull request by cesy**
Let's get some more stuff live, once we're happy with staging.

### CODE REVIEW

**Comment by Br3nda** [comment]
I'd like #1196 to make this release

**Comment by pozorvlak** [comment]
Looks good so far! @Br3nda, is this good to go, or are we waiting for another haml-escape PR from you?

**Comment by Br3nda** [comment]
Good to go.. can i push the button?

**Comment by maco** [comment]
Yep, go ahead!

**Comment by Br3nda** [comment]
Yay! deploying on a Friday!

**Comment by maco** [comment]
At least it's Thursday where I am?

**Pull request merged**
