### PR TITLE
Add SEO-friendly language to the crop detail page

### LINKED ISSUE #528: SEO: more searchable language on crop detail page
The crop detail page should have more search-friendly language, eg. "How to grow squash" rather than "Planting advice".  Especially, the first paragraph or so should say something about "Information about how to grow squash anywhere in the world" or something like that.

### PR DESCRIPTION
**Pull request by pozorvlak**
Fixes #528.

### CODE REVIEW

**Comment by tygriffin** [comment]
As we're updating content, would it make sense to extract strings to *config/locales/en.yml* piecemeal?

PS: I'm still not 100% certain how those locale files should be structured.

**Comment by Skud** [comment]
Hmmm. If we're not sure how to structure them let's not bother with extracting these strings right now, but let's have a discussion about it soon.

**Comment by Skud** [comment]
@tygriffin are you ok with this other than the to-be-figured-out i18n issue? can it be merged?

**Comment by tygriffin** [comment]
Good to go!

**Pull request merged**
