### PR TITLE
Fix author

### PR DESCRIPTION
**Pull request by maco**
My git author email was wrong on the commits that were merged today. Anyone feel ok about correcting history?

### CODE REVIEW

**Comment by maco** [comment]
(I'm actually really surprised it's not having merge issues about rewriting history)

**Comment by pozorvlak** [comment]
Unfortunately this didn't quite achieve what you wanted - both versions of the commit are now in the branch history. Steps to fix:

1. Someone needs to run `git push -f origin fix_author:dev` manually.
2. Everyone who's pulled the `dev` branch recently needs to run `git fetch origin dev; git checkout dev; git reset origin/dev`.

I'm happy to do step 1 if everyone else is OK with step 2.

**Comment by cesy** [comment]
Yes, since there are only 4 of us active enough to have pulled in the
meantime.

**Comment by pozorvlak** [comment]
OK, done. @CloCkWeRX, you'll need to adjust your dev branch as described above.

**Comment by maco** [comment]
Thanks, folks

**Pull request merged**
