### PR TITLE
Fix "fatal: Not a git repository" errors during deployment

### PR DESCRIPTION
**Pull request by pozorvlak**
An alternative approach would be to remove our vendor fork and add https://github.com/sideshowcoder/active_merchant-paypal-bogus-gateway to our Gemfile - @CloCkWeRX++ for contacting the original author!

### CODE REVIEW

**Comment by pozorvlak** [comment]
Here's the [blog post explaining why we have this gem under vendor/](http://web.archive.org/web/20151114104605/http://infotrope.net/2013/05/31/testing-paypal-express-with-activemerchants-bogusgateway-and-how-to-make-it-work/).

**Comment by CloCkWeRX** [comment]
+1 to this. Will redo #964 after this gets merged

**Comment by CloCkWeRX** [comment]
Much prefer removing the vendor directory (have plans to upgrade activemerchant anyway as part of rails 4.2 stuff)

**Comment by pozorvlak** [comment]
Yeah, I prefer removing the vendor directory too. I'll close this in favour of #974; if anyone strenuously objects, shout and I'll re-open this one :-)

**Pull request closed without merging**
