### PR TITLE
Add links to google, gardenate (for planting reminders)

### LINKED ISSUE #864: Prompt with planting reminders
Gardenate does this well: emailing to suggest what will be ready to plant.

See if there are open data sets or ways we can make it easy to know *when* to plant (and thus update growstuff).

Very similar to #524 but more distinctly about plants for your climate/region/etc.

image

Easiest implementation: link to gardenate so we don't double build the feature.

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #864 

While we could go and capture all of this data for ourselves/build similar features, for a lot less effort and an extra tool for users it's simpler to link to existing resources.

### CODE REVIEW

**Comment by pozorvlak** [comment]
Makes sense - could you add some simple tests to cover it?

**Comment by CloCkWeRX** [comment]
Tests added

**Comment by cesy** [comment]
Target blank has some security risks, sorry - can we go back to direct links without the target, please?

**Comment by cesy** [comment]
If you can fix the conflicts, I'll merge.

**Comment by CloCkWeRX** [comment]
Yeah no problems @cesy ... just have to figure out what they are!

**Pull request closed without merging**
