### PR TITLE
Reducing memory profile of the web app

### PR DESCRIPTION
**Pull request by Br3nda**
Remove newrelic - profiler says it's using a lot of memory, which is normally fine but we're over the 500MByte cap on heroku

Part of #1640

### CODE REVIEW

**Comment by Br3nda** [comment]
Removed bootstrap datepicker. the built in datepicker in a modern browser is just as good now.

**Comment by CloCkWeRX** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.
That's a bit worrying, hopefully flakey.

**Comment by Br3nda** [comment]
I'm not going to be sure we've reduced it yet. Only paid heroku tiers have metrics, Ave staging isn't paid

**Comment by Br3nda** [comment]
I'm gonna split this. Removing the datepicker is a bigger task, because the quick finish button does some nifty stuff.

**Comment by Br3nda** [comment]
i'll reopen this when it's ready

**Pull request closed without merging**
