### PR TITLE
Bundle Update on 2017-01-29

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [active_utils](http://github.com/shopify/active_utils), [3.2.3...3.2.4](https://github.com/shopify/active_utils/compare/v3.2.3...v3.2.4) ([CHANGELOG](https://github.com/Shopify/active_utils/blob/master/CHANGELOG.md))
- Updated: [activemerchant](http://github.com/activemerchant/active_merchant), [1.61.0...1.62.0](https://github.com/activemerchant/active_merchant/compare/v1.61.0...v1.62.0) ([CHANGELOG](https://github.com/activemerchant/active_merchant/blob/master/CHANGELOG))
- Updated: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), [6.6.1...6.7.0](https://github.com/ai/autoprefixer-rails/compare/6.6.1...6.7.0) ([CHANGELOG](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md))
- Updated: [bonsai-elasticsearch-rails](https://github.com/omc/bonsai-elasticsearch-rails), [0.0.4...0.2.0](https://github.com/omc/bonsai-elasticsearch-rails/compare/v0.0.4...v0.2.0)
- Updated: [capybara](http://github.com/jnicklas/capybara), [2.10.1...2.12.0](https://github.com/jnicklas/capybara/compare/2.10.1...2.12.0) ([CHANGELOG](https://github.com/jnicklas/capybara/blob/master/History.md))
- Updated: [childprocess](http://github.com/jarib/childprocess), [0.5.9...0.6.1](https://github.com/jarib/childprocess/compare/v0.5.9...v0.6.1)
- Updated: [codeclimate-test-reporter](https://github.com/codeclimate/ruby-test-reporter), [1.0.3...1.0.5](https://github.com/codeclimate/ruby-test-reporter/compare/v1.0.3...v1.0.5)
- Updated: [d3-rails](https://github.com/iblue/d3-rails), [3.4.13...4.3.0](https://github.com/iblue/d3-rails/compare/v3.4.13...v4.3.0) ([CHANGELOG](https://github.com/iblue/d3-rails/blob/master/CHANGELOG.md))
- Updated: [elasticsearch](http://github.com/elasticsearch/elasticsearch-ruby), [2.0.0...2.0.1](https://github.com/elasticsearch/elasticsearch-ruby/compare/v2.0.0...v2.0.1) ([CHANGELOG](https://github.com/elastic/elasticsearch-ruby/blob/master/CHANGELOG.md))
- Updated: [elasticsearch-api](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-api), [2.0.0...2.0.1](https://github.com/elasticsearch/elasticsearch-ruby/compare/v2.0.0...v2.0.1)
- Updated: [elasticsearch-transport](https://github.com/elasticsearch/elasticsearch-ruby/tree/master/elasticsearch-transport), [2.0.0...2.0.1](https://github.com/elasticsearch/elasticsearch-ruby/compare/v2.0.0...v2.0.1)
- Updated: [faraday](https://github.com/lostisland/faraday), [0.9.2...0.10.1](https://github.com/lostisland/faraday/compare/v0.9.2...v0.10.1) ([CHANGELOG](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md))
- Updated: [font-awesome-sass](https://github.com/FortAwesome/font-awesome-sass), [4.6.2...4.7.0](https://github.com/FortAwesome/font-awesome-sass/compare/v4.6.2...v4.7.0)
- Updated: html2haml, 2.0.0...2.1.0
- Updated: [js-routes](http://github.com/railsware/js-routes), [1.3.0...1.3.2](https://github.com/railsware/js-routes/compare/v1.3.0...v1.3.2) ([CHANGELOG](https://github.com/railsware/js-routes/blob/master/CHANGELOG.md))
- Updated: [kaminari](https://github.com/amatsuda/kaminari), [0.17.0...1.0.1](https://github.com/amatsuda/kaminari/compare/v0.17.0...v1.0.1) ([CHANGELOG](https://github.com/amatsuda/kaminari/blob/master/CHANGELOG.rdoc))
- Updated: kgio, 2.10.0...2.11.0 ([CHANGELOG](http://bogomips.org/kgio/NEWS.html))
- Updated: [leaflet-rails](https://github.com/axyjo/leaflet-rails), [0.7.7...1.0.2](https://github.com/axyjo/leaflet-rails/compare/v0.7.7...v1.0.2) ([CHANGELOG](https://github.com/axyjo/leaflet-rails/blob/master/CHANGELOG.md))
- Updated: [newrelic_rpm](http://github.com/newrelic/rpm), [3.17.1.326...3.18.0.329](https://github.com/newrelic/rpm/compare/3.17.1.326...3.18.0.329) ([CHANGELOG](https://github.com/newrelic/rpm/blob/master/CHANGELOG))
- Updated: [nokogiri](https://github.com/sparklemotion/nokogiri), [1.6.8.1...1.7.0.1](https://github.com/sparklemotion/nokogiri/compare/v1.6.8.1...v1.7.0.1) ([CHANGELOG](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md))
- Updated: [oauth2](http://github.com/intridea/oauth2), [1.2.0...1.3.0](https://github.com/intridea/oauth2/compare/v1.2.0...v1.3.0)
- Updated: [omniauth-twitter](https://github.com/arunagw/omniauth-twitter), [1.2.1...1.3.0](https://github.com/arunagw/omniauth-twitter/compare/v1.2.1...v1.3.0)
- Updated: [poltergeist](https://github.com/teampoltergeist/poltergeist), [1.11.0...1.13.0](https://github.com/teampoltergeist/poltergeist/compare/v1.11.0...v1.13.0) ([CHANGELOG](https://github.com/teampoltergeist/poltergeist/blob/master/CHANGELOG.md))
- Updated: [rb-inotify](http://github.com/nex3/rb-inotify), [0.9.7...0.9.8](https://github.com/nex3/rb-inotify/compare/v0.9.7...v0.9.8)
- Updated: [redis](https://github.com/redis/redis-rb), [3.3.2...3.3.3](https://github.com/redis/redis-rb/compare/v3.3.2...v3.3.3) ([CHANGELOG](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md))
- Updated: [ruby-units](https://github.com/olbrich/ruby-units), [2.0.1...2.1.0](https://github.com/olbrich/ruby-units/compare/v2.0.1...v2.1.0) ([CHANGELOG](https://github.com/olbrich/ruby-units/blob/master/CHANGELOG.txt))
- Updated: [sidekiq](https://github.com/mperham/sidekiq), [4.1.4...4.2.9](https://github.com/mperham/sidekiq/compare/v4.1.4...v4.2.9) ([CHANGELOG](https://github.com/mperham/sidekiq/blob/master/Changes.md))
- Updated: [tilt](http://github.com/rtomayko/tilt), [2.0.5...2.0.6](https://github.com/rtomayko/tilt/compare/v2.0.5...v2.0.6) ([CHANGELOG](https://github.com/rtomayko/tilt/blob/master/CHANGELOG.md))
- Updated: [unicorn](https://github.com/defunkt/unicorn), [5.1.0...5.2.0](https://github.com/defunkt/unicorn/compare/v5.1.0...v5.2.0) ([CHANGELOG](http://unicorn.bogomips.org/NEWS.html))
- Updated: [warden](http://github.com/hassox/warden), [1.2.6...1.2.7](https://github.com/hassox/warden/compare/v1.2.6...v1.2.7) ([CHANGELOG](https://github.com/hassox/warden/blob/master/History.rdoc))
- Updated: [websocket-driver](http://github.com/faye/websocket-driver-ruby), [0.6.4...0.6.5](https://github.com/faye/websocket-driver-ruby/compare/0.6.4...0.6.5) ([CHANGELOG](https://github.com/faye/websocket-driver-ruby/blob/master/CHANGELOG.md))
- Added: [jasmine](http://github.com/pivotal/jasmine-gem), [2.5.1](https://github.com/pivotal/jasmine-gem/tree/v2.5.1)
- Added: [jasmine-core](https://github.com/jasmine/jasmine), [2.5.2](https://github.com/jasmine/jasmine/tree/v2.5.2)
- Added: [kaminari-actionview](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [kaminari-activerecord](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [kaminari-core](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [phantomjs](https://github.com/colszowka/phantomjs-gem), [2.1.1.0](https://github.com/colszowka/phantomjs-gem/tree/v2.1.1.0)
- Removed: [sinatra](http://github.com/sinatra/sinatra), [1.4.7](https://github.com/sinatra/sinatra/tree/v1.4.7)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
1 Pull Request sent and 1 minute, and 23 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by Br3nda** [comment]
Those look like the same fails i'm getting in #1163

**Comment by pozorvlak** [comment]
Looks different to me. I see two JavaScript errors here:

```
 TypeError: undefined is not an object (evaluating 'd3.scale[scaleType]')
```

and

```
TypeError: undefined is not an object (evaluating 'str.trim')
```

I'll try to duplicate them locally.

**Comment by pozorvlak** [comment]
I'm getting a totally different error locally when I try to run `rspec ./spec/features/likeable_spec.rb`:

```
 1) Likeable logged in member displays correct number of likes
     Failure/Error: expect(page).to have_content '1 like'
       expected to find text "1 like" in "Routing Error Site Not Found Rails.root: /home/mgould/src/growstuff Application Trace | Framework Trace | Full Trace Routes Routes match in priority from top to bottom Helper HTTP Verb Path Controller#Action Path
[snip very long dump of routing table]
```

Here's a screenshot of my reproducing the problem manually:

screenshot from 2017-01-30 21-10-53

The `likes.json` callback is trying to load the CMS, but since I don't have any CMS sites defined in my test database the CMS is complaining.

**Comment by pozorvlak** [comment]
`LikesController` only handles POST and DELETE requests, but for some reason the test is making a GET request. This is falling through the routes table until it hits our CMS route, which is "everything else under /". Then it hits that bit of code in `comfortable_mexican_sofa` which checks the path against the pages in the CMS, says "nope, I don't have a page called 'likes'" and dies.

So my problem is actually

 - the "Like" link doesn't gracefully degrade in the absence of JavaScript
 - my tests aren't being run with JS enabled.

**Comment by CloCkWeRX** [comment]
Going to close this one off and do a different PR, upgrading fewer gems - see if we can pin down the precise bit that makes it angry.

**Comment by CloCkWeRX** [comment]
Interesting - no matter what I bundle update, I get poltergeist/jasmine added to my Gemfile.lock; which are absent from the current dev branch.

**Pull request closed without merging**
