### PR TITLE
Bundle Update on 2017-02-12

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [active_utils](http://github.com/shopify/active_utils), [3.2.3...3.2.5](https://github.com/shopify/active_utils/compare/v3.2.3...v3.2.5) ([CHANGELOG](https://github.com/Shopify/active_utils/blob/master/CHANGELOG.md))
- Updated: [activemerchant](http://github.com/activemerchant/active_merchant), [1.61.0...1.63.0](https://github.com/activemerchant/active_merchant/compare/v1.61.0...v1.63.0) ([CHANGELOG](https://github.com/activemerchant/active_merchant/blob/master/CHANGELOG))
- Updated: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), [6.6.1...6.7.2](https://github.com/ai/autoprefixer-rails/compare/6.6.1...6.7.2) ([CHANGELOG](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md))
- Updated: [bonsai-elasticsearch-rails](https://github.com/omc/bonsai-elasticsearch-rails), [0.0.4...0.2.0](https://github.com/omc/bonsai-elasticsearch-rails/compare/v0.0.4...v0.2.0)
- Updated: [bootstrap_form](http://github.com/bootstrap-ruby/rails-bootstrap-forms), [2.5.3...2.6.0](https://github.com/bootstrap-ruby/rails-bootstrap-forms/compare/v2.5.3...v2.6.0) ([CHANGELOG](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/CHANGELOG.md))
- Updated: [cancancan](https://github.com/CanCanCommunity/cancancan), [1.15.0...1.16.0](https://github.com/CanCanCommunity/cancancan/compare/v1.15.0...v1.16.0) ([CHANGELOG](https://github.com/CanCanCommunity/cancancan/blob/develop/CHANGELOG.rdoc))
- Updated: [capybara](http://github.com/jnicklas/capybara), [2.10.1...2.12.0](https://github.com/jnicklas/capybara/compare/2.10.1...2.12.0) ([CHANGELOG](https://github.com/jnicklas/capybara/blob/master/History.md))
- Updated: [childprocess](http://github.com/jarib/childprocess), [0.5.9...0.6.1](https://github.com/jarib/childprocess/compare/v0.5.9...v0.6.1)
- Updated: [codeclimate-test-reporter](https://github.com/codeclimate/ruby-test-reporter), [1.0.3...1.0.5](https://github.com/codeclimate/ruby-test-reporter/compare/v1.0.3...v1.0.5)
- Updated: [d3-rails](https://github.com/iblue/d3-rails), [3.4.13...4.3.0](https://github.com/iblue/d3-rails/compare/v3.4.13...v4.3.0) ([CHANGELOG](https://github.com/iblue/d3-rails/blob/master/CHANGELOG.md))
- Updated: [elasticsearch](http://github.com/elasticsearch/elasticsearch-ruby), [2.0.0...2.0.1](https://github.com/elasticsearch/elasticsearch-ruby/compare/v2.0.0...v2.0.1) ([CHANGELOG](https://github.com/elastic/elasticsearch-ruby/blob/master/CHANGELOG.md))
- Updated: [elasticsearch-api](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-api), [2.0.0...2.0.1](https://github.com/elasticsearch/elasticsearch-ruby/compare/v2.0.0...v2.0.1)
- Updated: [elasticsearch-transport](https://github.com/elasticsearch/elasticsearch-ruby/tree/master/elasticsearch-transport), [2.0.0...2.0.1](https://github.com/elasticsearch/elasticsearch-ruby/compare/v2.0.0...v2.0.1)
- Updated: [excon](https://github.com/excon/excon), [0.54.0...0.55.0](https://github.com/excon/excon/compare/v0.54.0...v0.55.0) ([CHANGELOG](https://github.com/excon/excon/blob/master/changelog.txt))
- Updated: [faraday](https://github.com/lostisland/faraday), [0.9.2...0.10.1](https://github.com/lostisland/faraday/compare/v0.9.2...v0.10.1) ([CHANGELOG](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md))
- Updated: [font-awesome-sass](https://github.com/FortAwesome/font-awesome-sass), [4.6.2...4.7.0](https://github.com/FortAwesome/font-awesome-sass/compare/v4.6.2...v4.7.0)
- Updated: [geocoder](https://github.com/alexreisner/geocoder), [1.4.1...1.4.3](https://github.com/alexreisner/geocoder/compare/v1.4.1...v1.4.3) ([CHANGELOG](https://github.com/alexreisner/geocoder/blob/master/CHANGELOG.md))
- Updated: [guard](https://github.com/guard/guard), [2.14.0...2.14.1](https://github.com/guard/guard/compare/v2.14.0...v2.14.1) ([CHANGELOG](https://github.com/guard/guard/blob/master/CHANGELOG.md))
- Updated: [hashie](https://github.com/intridea/hashie), [3.4.6...3.5.2](https://github.com/intridea/hashie/compare/v3.4.6...v3.5.2) ([CHANGELOG](https://github.com/intridea/hashie/blob/master/CHANGELOG.md))
- Updated: html2haml, 2.0.0...2.1.0
- Updated: [i18n](http://github.com/svenfuchs/i18n), [0.7.0...0.8.0](https://github.com/svenfuchs/i18n/compare/v0.7.0...v0.8.0) ([CHANGELOG](https://github.com/svenfuchs/i18n/blob/master/CHANGELOG.md))
- Updated: [i18n-tasks](https://github.com/glebm/i18n-tasks), [0.9.9...0.9.11](https://github.com/glebm/i18n-tasks/compare/v0.9.9...v0.9.11) ([CHANGELOG](https://github.com/glebm/i18n-tasks/blob/master/CHANGES.md))
- Updated: [js-routes](http://github.com/railsware/js-routes), [1.3.0...1.3.2](https://github.com/railsware/js-routes/compare/v1.3.0...v1.3.2) ([CHANGELOG](https://github.com/railsware/js-routes/blob/master/CHANGELOG.md))
- Updated: [kaminari](https://github.com/amatsuda/kaminari), [0.17.0...1.0.1](https://github.com/amatsuda/kaminari/compare/v0.17.0...v1.0.1) ([CHANGELOG](https://github.com/amatsuda/kaminari/blob/master/CHANGELOG.rdoc))
- Updated: kgio, 2.10.0...2.11.0 ([CHANGELOG](http://bogomips.org/kgio/NEWS.html))
- Updated: [leaflet-rails](https://github.com/axyjo/leaflet-rails), [0.7.7...1.0.2](https://github.com/axyjo/leaflet-rails/compare/v0.7.7...v1.0.2) ([CHANGELOG](https://github.com/axyjo/leaflet-rails/blob/master/CHANGELOG.md))
- Updated: [newrelic_rpm](http://github.com/newrelic/rpm), [3.17.1.326...3.18.1.330](https://github.com/newrelic/rpm/compare/3.17.1.326...3.18.1.330) ([CHANGELOG](https://github.com/newrelic/rpm/blob/master/CHANGELOG))
- Updated: [nokogiri](https://github.com/sparklemotion/nokogiri), [1.6.8.1...1.7.0.1](https://github.com/sparklemotion/nokogiri/compare/v1.6.8.1...v1.7.0.1) ([CHANGELOG](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md))
- Updated: [oauth2](http://github.com/intridea/oauth2), [1.2.0...1.3.0](https://github.com/intridea/oauth2/compare/v1.2.0...v1.3.0)
- Updated: [omniauth](http://github.com/intridea/omniauth), [1.3.2...1.4.1](https://github.com/intridea/omniauth/compare/v1.3.2...v1.4.1)
- Updated: [omniauth-twitter](https://github.com/arunagw/omniauth-twitter), [1.2.1...1.4.0](https://github.com/arunagw/omniauth-twitter/compare/v1.2.1...v1.4.0)
- Updated: [parser](https://github.com/whitequark/parser), [2.3.3.1...2.4.0.0](https://github.com/whitequark/parser/compare/v2.3.3.1...v2.4.0.0) ([CHANGELOG](https://github.com/whitequark/parser/blob/master/CHANGELOG.md))
- Updated: [poltergeist](https://github.com/teampoltergeist/poltergeist), [1.11.0...1.13.0](https://github.com/teampoltergeist/poltergeist/compare/v1.11.0...v1.13.0) ([CHANGELOG](https://github.com/teampoltergeist/poltergeist/blob/master/CHANGELOG.md))
- Updated: [rb-inotify](http://github.com/nex3/rb-inotify), [0.9.7...0.9.8](https://github.com/nex3/rb-inotify/compare/v0.9.7...v0.9.8)
- Updated: [redis](https://github.com/redis/redis-rb), [3.3.2...3.3.3](https://github.com/redis/redis-rb/compare/v3.3.2...v3.3.3) ([CHANGELOG](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md))
- Updated: [ruby-units](https://github.com/olbrich/ruby-units), [2.0.1...2.1.0](https://github.com/olbrich/ruby-units/compare/v2.0.1...v2.1.0) ([CHANGELOG](https://github.com/olbrich/ruby-units/blob/master/CHANGELOG.txt))
- Updated: [rubyzip](http://github.com/rubyzip/rubyzip), [1.2.0...1.2.1](https://github.com/rubyzip/rubyzip/compare/v1.2.0...v1.2.1) ([CHANGELOG](https://github.com/rubyzip/rubyzip/blob/master/Changelog.md))
- Updated: [selenium-webdriver](https://github.com/seleniumhq/selenium), [3.0.5...3.0.8](https://github.com/seleniumhq/selenium/compare/selenium-3.0.5...selenium-3.0.8)
- Updated: [sexp_processor](https://github.com/seattlerb/sexp_processor), [4.7.0...4.8.0](https://github.com/seattlerb/sexp_processor/compare/v4.7.0...v4.8.0) ([CHANGELOG](https://github.com/seattlerb/sexp_processor/blob/master/History.txt))
- Updated: [sidekiq](https://github.com/mperham/sidekiq), [4.1.4...4.2.9](https://github.com/mperham/sidekiq/compare/v4.1.4...v4.2.9) ([CHANGELOG](https://github.com/mperham/sidekiq/blob/master/Changes.md))
- Updated: [tilt](http://github.com/rtomayko/tilt), [2.0.5...2.0.6](https://github.com/rtomayko/tilt/compare/v2.0.5...v2.0.6) ([CHANGELOG](https://github.com/rtomayko/tilt/blob/master/CHANGELOG.md))
- Updated: [tins](https://github.com/flori/tins), [1.13.0...1.13.2](https://github.com/flori/tins/compare/v1.13.0...v1.13.2)
- Updated: [unicorn](https://github.com/defunkt/unicorn), [5.1.0...5.2.0](https://github.com/defunkt/unicorn/compare/v5.1.0...v5.2.0) ([CHANGELOG](http://unicorn.bogomips.org/NEWS.html))
- Updated: [warden](http://github.com/hassox/warden), [1.2.6...1.2.7](https://github.com/hassox/warden/compare/v1.2.6...v1.2.7) ([CHANGELOG](https://github.com/hassox/warden/blob/master/History.rdoc))
- Updated: [websocket](http://github.com/imanel/websocket-ruby), [1.2.3...1.2.4](https://github.com/imanel/websocket-ruby/compare/v1.2.3...v1.2.4) ([CHANGELOG](https://github.com/imanel/websocket-ruby/blob/master/CHANGELOG.md))
- Updated: [websocket-driver](http://github.com/faye/websocket-driver-ruby), [0.6.4...0.6.5](https://github.com/faye/websocket-driver-ruby/compare/0.6.4...0.6.5) ([CHANGELOG](https://github.com/faye/websocket-driver-ruby/blob/master/CHANGELOG.md))
- Added: [kaminari-actionview](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [kaminari-activerecord](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [kaminari-core](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Removed: [sinatra](http://github.com/sinatra/sinatra), [1.4.7](https://github.com/sinatra/sinatra/tree/v1.4.7)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
2 Pull Requests sent and 3 minutes, and 22 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by pozorvlak** [comment]
```
Bundler::GemRequireError: There was an error while trying to load the gem 'omniauth-facebook'.
Gem Load Error is: private method `warn' called for nil:NilClass
Backtrace for gem load error is:
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:334:in `log_built_in_message'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:139:in `custom_writer'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:207:in `block in deep_update'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `each_pair'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.3.0/gems/hashie-3.5.2/lib/hashie/mash.rb:200:in `deep_update'
[snip]
```

**Comment by CloCkWeRX** [comment]
http://stackoverflow.com/questions/42170666/bundlergemrequireerror-there-was-an-error-while-trying-to-load-the-gem-omnia seems to be the only other thing I can find on it. I'll pin one or the other to a working version shortly :)

**Comment by CloCkWeRX** [comment]
https://github.com/intridea/hashie/issues/408 raised

**Comment by CloCkWeRX** [comment]
https://github.com/intridea/hashie/issues/401

**Comment by CloCkWeRX** [comment]
Well, there's a bit much here to work out the cause of the regression easily; so going to replace this with a different PR to upgrade some gems incrementally.

**Pull request closed without merging**
