### PR TITLE
Fix Growstuff::OauthSignupAction not found error when connecting flickr

### LINKED ISSUE #1479: Connect / login by twitter and Facebook broken
As a new member editing my profile, I want to be able to connect to Twitter, Flikr or Facebook when clicking the icons so that I can link my profile to those accounts.
Current behaviour: the links to make to a page showing that the page I am looking for does not exist.
Desired behaviour: the links should take me to the social media page.
Bugs captured using bugReplay: https://app.bugreplay.com/shared/report/3864db91-3bb2-4a2f-91c3-38e09ed4a603

### PR DESCRIPTION
**Pull request by Br3nda**
also fixes #1479 
(someone please test FB, i don't have an account)

### CODE REVIEW

**Comment by pozorvlak** [comment]
LGTM; I'll check login-with-Facebook once this has deployed on staging.

**Comment by Br3nda** [comment]
twitter worked on staging.

**Comment by pozorvlak** [comment]
Sign-in with Facebook now works on staging.

**Comment by Br3nda** [comment]
it's in prod too!

**Pull request merged**
