### PR TITLE
Show roles in member profile page

### LINKED ISSUE #557: Show roles (admin, crop wrangler) on profile page
If someone is an admin or crop wrangler this should show on their profile page.

### PR DESCRIPTION
**Pull request by twconquest**
Fixes #557. Takes @jacemonje's work from #767 and tests with feature test.

### CODE REVIEW

**Comment by cesy** [comment]
Ideally we should also include negative tests that a non-crop wrangler's page doesn't say crop wrangler, and so on. Thank you for picking this up, and it's good to merge, but would be better still with a couple of extra tests if you have time.

**Comment by pozorvlak** [comment]
Good point! @twconquest and I were planning another pairing session soon, we should be able to fix that.

**Comment by pozorvlak** [comment]
@cesy we've added a negative test along the lines you suggested.

**Comment by cesy** [comment]
Great, thanks!

**Pull request merged**
