### PR TITLE
Add fork me on github ribbon, but smaller so the logo isn't clobbered

### LINKED ISSUE #1014: Add "fork me on github" banner
@pozorvlak hmm alignment's a little odd there...think it's ok?

(note to self: this involved `z-index: 2000` on the banner image to get it over the nav bar)

screen shot 2016-06-22 at 12 07 04 pm

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #1014

### CODE REVIEW

**Comment by pozorvlak** [comment]
It still overlaps for me at some widths:

growstuff_fork_overlap

I'm tempted to say "let's just live with it".

**Comment by pozorvlak** [comment]
Capybara agrees:

```
  1) Notifications pagination navigates pages
     Failure/Error: first('a[rel="next"]').click
     
     Capybara::Poltergeist::MouseEventFailed:
       Firing a click at co-ordinates [92, 156.5] failed. Poltergeist detected another element with CSS selector 'html body span#forkongithub' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
     # ./spec/features/notifications_spec.rb:48:in `block (3 levels) in <top (required)>'
```

**Comment by CloCkWeRX** [comment]
Its kinda annoying. Maybe we just oompf up the footer links - maybe a social media icon like the facebook/twitter/etc ones?

**Comment by cesy** [comment]
Yeah, I'm inclined to skip the ribbon, since it's confusing for users who
don't know what github is.

**Pull request closed without merging**
