### PR TITLE
upgrade gems and make API change for ruby-units

### PR DESCRIPTION
**Pull request by maco**
Locked gibbon to 1.2.x also, because if it upgrades to 2.x, it switches to the new MailChimp API, and the devs went "while we're changing API anyway..." and changed the gibbon API too, so... 😒 at the very least application.rb would need some changes, and I don't know what all else.

### CODE REVIEW

**Comment by cesy** [comment]
I think it might make more sense to split out the three separate issues here. I'm not quite clear on why we want to ignore public, either.

**Comment by maco** [comment]
public/ is where the generated stuff that happens each time you run "rails
server" or "rake assets:precompile" go. I was afraid "git commit -a" was
going to catch it.

The API change for ruby-units was part of making the result of "bundle
update" work. If I just did "bundle update" and committed, Travis would've
grumped at us.

**Comment by maco** [comment]
Want me to make a PR that upgrades all the gems _except_ ruby-units?

**Comment by pozorvlak** [comment]
I'm happy for the `ruby-units` change to be included since it's required by the library upgrade, but I'd prefer it if the change to `.gitignore` to be split out.

**Comment by cesy** [comment]
Public is also where our error pages are, though, and we want to keep changes to them. So we'd need a more specific pattern for the bits we want to ignore.

Happy to include ruby-units based on this, though.

**Comment by maco** [comment]
updated the diff

**Comment by pozorvlak** [comment]
I think this means we've now merged all the "upgrade dependencies" patches
for release 10, so we should do another deployment soon. I'm around this
afternoon, from about 4pm UK time, or tomorrow evening.

**Comment by maco** [comment]
:+1:

Now let's see if emailing emoji codes works

**Comment by cesy** [comment]
4pm is good for me.

**Pull request merged**
