### PR TITLE
Added multiple forms for scientific and alternate names on crop creation  (Fixes #615)

### LINKED ISSUE #615: "New crop" form needs fields for alternate names
We added infrastructure for alternate names but we have no easy way to add them at the same time as creating a new crop.  We should have fields for alt names (probably half a dozen of them! some crops have lots of names!) on the crops/new form, same as for scientific names.

### PR DESCRIPTION
**Pull request by GabrielSandoval**
Hi,

I paired with @jacarandang to fix this issue. Here's the new crop page form:

screen shot 2015-07-13 at 2 14 21 pm

Any say to this?

Gabriel Sandoval, Jym Paul Carandang
AELOGICA Interns

### CODE REVIEW

**Comment by GabrielSandoval** [comment]
Have you checked this @pozorvlak , @cesy , and @maco ?

**Comment by pozorvlak** [comment]
Not yet, sorry - I'm currently suffering from an attack of life, but am expecting to do some more Growstuff work on Thursday. Your screenshots look good, though!

**Comment by pozorvlak** [comment]
Finally managed to get a look at this - great stuff! I see this works with JavaScript turned off, which is great - [accessibility](http://wiki.growstuff.org/index.php/Accessibility) is important to us - but the +/- buttons are still present and non-functional. It would be better if they were hidden by default and made visible by JavaScript code. Otherwise, looks good.

**Comment by GabrielSandoval** [comment]
All done @pozorvlak :+1:

**Pull request merged**
