### PR TITLE
Bump ruby version to 2.4.1

### PR DESCRIPTION
**Pull request by Br3nda**
Note: if you don't specify a ruby version in`.travis.yml`, Travis will read `.ruby-version`
this is a little less repeating ourselves.

### CODE REVIEW

**Comment by Br3nda** [comment]
i propose we merge this instead of #1386

**Comment by cesy** [comment]
Brilliant, it would be good to get a bit more up-to-date. Thanks!

**Comment by cesy** [comment]
Travis failures need looking at, though.

**Comment by pozorvlak** [comment]
According to https://stackoverflow.com/a/42277075, it should be enough to
add `gem 'xmlrpc'` to our Gemfile.

**Comment by Br3nda** [comment]
any idea what we use the xmlrpc client for?

**Comment by pozorvlak** [comment]
Looks ​like it's Gravatar:

```
LoadError: cannot load such file -- xmlrpc/client
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in
`require'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in
`block in require'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in
`load_dependency'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in
`require'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.4.0/gems/gravatar-ultimate-2.0.0/lib/gravatar/dependencies.rb:5:in
`<top (required)>'
/home/travis/build/Growstuff/growstuff/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in
`require'
[snip]
```

**Comment by cesy** [comment]
Does it need match rather than matches? Travis still failing.

**Comment by Br3nda** [comment]
Maybe... but i swear rspec passed before i pushed.

**Comment by Br3nda** [comment]
> In Ruby 2.4, `String#match?`, `Regexp#match?` and `Symbol#match?` have been added. The methods are faster than `match`. Because the methods avoid creating a `MatchData` object or saving backref. So, when `MatchData` is not used, use `match?` instead of `match`.

cool.

But I'll use `.start_with?` because it seems more pythonic :-D

**Comment by Br3nda** [comment]
It's all passing. Can we merge?

**Comment by cesy** [comment]
Sorry for the delay, yes, this is fine.

**Pull request merged**
