### PR TITLE
Turn on Phantom JS for all tests

### PR DESCRIPTION
**Pull request by cesy**
Another attempt at turning on Javascript for more of our tests. Based on #670 by @pozorvlak, with a few further fixes. Ready for merge - all tests passing.

### CODE REVIEW

**Comment by cesy** [comment]
@pozorvlak if you had time to review this, that would be great - it'll make my delete work easier once it's merged.

**Comment by pozorvlak** [comment]
@cesy: I'm busy right now, but will try to take a look this evening. Sorry for the delay!

@CloCkWeRX: accessibility is a big deal for us, so it's essential that everything works without JavaScript.

**Comment by pozorvlak** [comment]
@cesy: looks great!

**Comment by CloCkWeRX** [comment]
> Do you mean explanation of why both JS-on and JS-off matter
Yeah - right now its describing a 'how' not a 'why', if that makes sense. It's pretty similar to http://betterspecs.org/#contexts - I'd be tempted to make a bunch of contexts like "admin user", "admin user with javascript disabled for accessability reasons", etc if it were more than 2-3 spots.

Anywho; merged now :)

**Comment by cesy** [comment]
Okay, that makes sense - commentary added to clarify in #822.

**Pull request merged**
