### PR TITLE
Removing shop, products, accounts, orders

### LINKED ISSUE #1552: Is it time to remove paid account functionality?
I don't think it works. I can't actually check out an order.
Could we do better with patreon or other subscription, not managed without our code.

### PR DESCRIPTION
**Pull request by Br3nda**
Pushing branch now so CI can run.

closes #1552

### CODE REVIEW

**Comment by Br3nda** [comment]
I think this will make the rails 5 upgrades easier. Much less code to fix up.

**Comment by CloCkWeRX** [comment]
Can we safely remove the activemerchant gem too?

**Comment by Br3nda** [comment]
Oh I thought I did. Forgot to push

**Comment by Br3nda** [comment]
pushed -- also removed config

**Comment by Br3nda** [comment]
isn't it beautiful, how little code is left?

**Pull request merged**
