### PR TITLE
Prevent FactoryGirl from trying to connect to ElasticSearch in tests

### LINKED ISSUE #1047: Failed to open TCP connection to localhost:9200
when i run the specs i get 100+ tests failing with  Failed to open TCP connection to localhost:9200
Is this for elastic search? the comments in application.yml.example lead me to thing this isn't needed to run the app or the tests.

I have config/application.yml, with GROWSTUFF_ELASTICSEARCH: "false"

Is it supposed to be possible to run the specs without elastic search?
Are there instructions somewhere on setting up elastic search for dev,test,ci?

---
p.s. typed with a small child pulling on my arm. forgive typoss.

### PR DESCRIPTION
**Pull request by pozorvlak**
Fixes #1047.

### CODE REVIEW

**Comment by cesy** [comment]
Have you set the new env variable in Heroku stage and prod? Do we need to document it anywhere else, e.g. putting it to false in our example .yml so other people can use our code without getting caught out by it?

Travis failures were just Poltergeist, so this is otherwise good to go.

**Comment by pozorvlak** [comment]
I didn't add an environment variable, I just added an additional check for
one we were already using.

**Comment by CloCkWeRX** [comment]
Oophf, I get why it works, I just get sad that we have hooks like this :( 

Longer term, are we better off explicitly calling update_index from a controller; rather than relying on after_* ?

In my experience, this initially sounds like a bad idea but ends up being only a handful of places where we are being explicit in an controller or two - and that tends to be a better spot to look at config/env vars to change behaviour (wiring)

Maybe if we get bitten a few more times, worth another look

**Comment by pozorvlak** [comment]
Agreed, this is pretty ugly, and your suggestion is definitely worth
bearing in mind for the future.

Honestly, though, I think the best solution is "make setting up an
environment containing ElasticSearch trivially easy, and then remove all
the non-ES code".

**Pull request merged**
