### PR TITLE
Align links properly on "Forgot password page", "Resend confirmation" and "Resend unlock" pages

### PR DESCRIPTION
**Pull request by dv2**

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Code LGTM, any chance of a quick screenshot of what it looks like now?

**Comment by dv2** [comment]
@CloCkWeRX Screenshots attached

screen shot 2016-05-29 at 8 01 20 pm
screen shot 2016-05-29 at 8 02 01 pm
screen shot 2016-05-29 at 8 02 12 pm

**Comment by pozorvlak** [comment]
Looks good to me! @dv2, can you please add yourself to CONTRIBUTORS.md?

**Comment by dv2** [comment]
@pozorvlak Added me to CONTRIBUTORS.md, please check. Thanks

**Comment by pozorvlak** [comment]
Thanks, and welcome to the project!

**Pull request merged**
