### PR TITLE
Deal with .nil quantity of a seed in rendering helper

### PR DESCRIPTION
**Pull request by CloCkWeRX**
For #920 

Will go write explicit coverage of the helper in a bit, if this is the actual issue.

### CODE REVIEW

**Comment by cesy** [comment]
It would also be good to have a feature test of the steps you did to create it on staging.

**Comment by pozorvlak** [comment]
"Request to 'http://127.0.0.1:8081' failed to reach server, check DNS and/or server status" again :-( It looks like [this StackOverflow post](http://stackoverflow.com/questions/35743167/capybarapoltergeist-status-error-failed-to-reach-server) may have a fix - I'll try it out.

**Comment by pozorvlak** [comment]
Running the tests locally without a network connection didn't produce any failures, so I don't think that can be the problem :-(

**Comment by maco** [comment]
127.0.0.1 wouldn't depend on your network connection. That's localhost.

**Comment by pozorvlak** [comment]
@maco yes, but [some people suggested](https://github.com/teampoltergeist/poltergeist/issues/375#issuecomment-42620085) that that message was erroneous, and the error could be caused by a remote resource timing out. But since the tests run fine without a network connection, that can't be the problem, which means the solution in the link I posted won't help.

**Comment by maco** [comment]
Ah I only looked at the SO link, which mentioned something about
firewalling 127.0.0.1

**Comment by pozorvlak** [comment]
@CloCkWeRX: looks good, please add tests.

**Pull request merged**
