### PR TITLE
WIP: add require_relative to photo_capable concern for constants

### PR DESCRIPTION
**Pull request by maco**
starts #1107 
need to add require changes in photo.rb and photos_controller.rb but can't really test until #1106 is fixed

### CODE REVIEW

**Comment by Br3nda** [comment]
This does fix the error.
Maybe a feature spec for the plantings#new page will catch this in the future.

**Comment by maco** [comment]
@Br3nda ok, so photo.rb and photos_controller.rb are fine as they are? That seems surprising.

**Comment by Br3nda** [comment]
i'm getting this error from dev branch
```
NameError - uninitialized constant Growstuff::Constants:
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:184:in `const_missing'
  app/models/photo.rb:4:in `<class:Photo>'
  app/models/photo.rb:1:in `<top (required)>'
```

the specs fail too...

cherry-pick this PR's commit fixes it.

**Comment by maco** [comment]
There's probably some way to make it autoload so it's not repeatedly loaded to make that warning, but merging this so we go from error to warning is probably a good step

**Comment by CloCkWeRX** [comment]
Perhaps 13dd20c8ff603d4155978b2b863c985a4bfdc43d kills the warning a bit better (still no autoload)

**Pull request merged**
