### PR TITLE
Homepage layout

### LINKED ISSUE #2020: Location too long on member cards
image

### PR DESCRIPTION
**Pull request by Br3nda**
Fix up layout on home page, including truncating long locations like taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu

fixes #2020

### CODE REVIEW

**Comment by pozorvlak** [comment]
Representative unit-test failures:
```
3) home/_members.html.haml Shows members 
     Failure/Error: - members = Member.includes(plantings: :crop).interesting.limit(max)
     
     ActionView::Template::Error:
       undefined local variable or method `max' for #<#<Class:0x000000000a0a3610>:0x00007f39188e71e8>
       Did you mean?  map
     # ./app/views/home/_members.html.haml:3:in `block in _app_views_home__members_html_haml___1075108729222557482_69941632389560'
     # ./app/views/home/_members.html.haml:1:in `_app_views_home__members_html_haml___1075108729222557482_69941632389560'
     # ./spec/views/home/_members.html.haml_spec.rb:10:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NameError:
     #   undefined local variable or method `max' for #<#<Class:0x000000000a0a3610>:0x00007f39188e71e8>
     #   Did you mean?  map
     #   ./app/views/home/_members.html.haml:3:in `block in _app_views_home__members_html_haml___1075108729222557482_69941632389560'

  4) home/_seeds.html.haml 
     Failure/Error: - Seed.current.tradable.includes(:owner, :crop).order(created_at: :desc).limit(max).each do |seed|
     
     ActionView::Template::Error:
       undefined local variable or method `max' for #<#<Class:0x000000000a0a3610>:0x00000000059c90c8>
       Did you mean?  map
     # ./app/views/home/_seeds.html.haml:4:in `block in _app_views_home__seeds_html_haml___3669564562688326908_90177460'
     # ./app/views/home/_seeds.html.haml:1:in `_app_views_home__seeds_html_haml___3669564562688326908_90177460'
     # ./spec/views/home/_seeds.html.haml_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NameError:
     #   undefined local variable or method `max' for #<#<Class:0x000000000a0a3610>:0x00000000059c90c8>
     #   Did you mean?  map
     #   ./app/views/home/_seeds.html.haml:4:in `block in _app_views_home__seeds_html_haml___3669564562688326908_90177460'
```

**Comment by pozorvlak** [comment]
Looks like you need to add `locals: { max: 6 }` to the `render` calls in `_members.html.haml_spec.rb` and `_seeds.html.haml_spec.rb`.

**Comment by pozorvlak** [comment]
We should also probably have some tests for `home/_discuss.html.haml` - there's nothing specific to test it, and the tests in `home/index_spec.rb` don't appear to check that posts are rendered correctly (or much else, come to that).

**Comment by Br3nda** [comment]
backed out the max: change for now. Rebased

**Pull request merged**
