### PR TITLE
Removing pre-commit.sh script

### PR DESCRIPTION
**Pull request by Br3nda**
This doesn't appear to be used anywhere. Can it go?

### CODE REVIEW

**Comment by Br3nda** [comment]
git log shows these:

```
 commit 15ce32e786ea0570c60f3e378796165415b7abde
 Author: Miles Gould 
 Date:   Mon Sep 10 17:41:09 2012 +0100
 
     Only stash unindexed changes if there are any.
     
     This allows `git commit --amend` to work properly.
 
 commit b173aad6b763b04e481b74dd72df696fb95f9856
 Author: Miles Gould 
 Date:   Mon Sep 10 15:28:42 2012 +0100
 
     Added pre-commit hook script to run spec tests.
     
     Based on instructions found at
     http://codeinthehole.com/writing/tips-for-using-a-git-pre-commit-hook/
     
     I have no idea how portable this will be.
```

**Comment by pozorvlak** [comment]
Yeah, kill it - I don't think anyone was using it, and it's now been
comprehensively superseded by overcommit.

**Comment by pozorvlak** [comment]
Static checks failing for an unrelated reason:

```
Analyze with ESLint..........................................[EsLint] FAILED

/home/travis/build/Growstuff/growstuff/node_modules/eslint/bin/eslint.js:16

const useStdIn = (process.argv.indexOf("--stdin") > -1),

^^^^^

SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by pozorvlak** [comment]
This is apparently due to [using an old version of node.js](http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode).

**Pull request merged**
