### PR TITLE
don't override our environment email settings with plain old sendmail

### PR DESCRIPTION
**Pull request by maco**
We were actually trying to send from the local server instance's install of sendmail

### CODE REVIEW

**Comment by pozorvlak** [comment]
Looks like that code's been in there since 2012 - how did email ever work?

**Comment by maco** [comment]
How email ever worked: our SPF record appears to say something along the
lines of "and any IP address heroku could ever possibly use is fine too" so
uh...i'll be fixing that.

**Comment by pozorvlak** [comment]
I'm still confused, though:

```
$ heroku run --app=growstuff-staging ls -l /usr/sbin/sendmail
ls: cannot access /usr/sbin/sendmail: No such file or directory
$ heroku run --app=growstuff-prod ls -l /usr/sbin/sendmail
ls: cannot access /usr/sbin/sendmail: No such file or directory
```

So there isn't a `/usr/sbin/sendmail` on either our production or staging environments. Unless that's only become true recently, I don't think we can have been using sendmail to send out email.

**Comment by maco** [comment]
Maybe heroku did recently remove it *shrug*

**Pull request merged**
