### PR TITLE
Truncate, escape, and DRY og:description fields

### PR DESCRIPTION
**Pull request by Br3nda**

### CODE REVIEW

**Comment by Br3nda** [comment]
Let's put this on master too?

**Comment by Br3nda** [comment]
or is the release gonna go today anyways?

**Comment by maco** [comment]
Sounds good to me. Probably takes a second PR.

**Comment by maco** [comment]
Release'll definitely go soon...I don't know if today or tomorrow.

**Comment by Br3nda** [comment]
No good - there's other changes that need to go in application_helper first, or the dev -> master branch merge will get messy.

Let's wait another day.

**Pull request merged**
