### PR TITLE
issue #658 i18n automation 

### PR DESCRIPTION
**Pull request by jestallin**

### CODE REVIEW

**Comment by jestallin** [comment]
#658

**Comment by cesy** [comment]
This looks like a really good tool. It should probably have a second reviewer as it's a change to the way we're doing things, and we'll need to review the output carefully for each file we do it on, but I love it.

**Comment by cesy** [comment]
We've got some conflicts in the gemfile, but we're now finally at a point where this could be merged - would you mind updating it, please? We're getting more regular deploys to production these days.

**Comment by maco** [comment]
:+1: from me too

**Comment by jestallin** [comment]
I will take a look at what has changed. Thanks!

**Comment by cesy** [comment]
This would be great to include if you can resolve the conflicts, please.

**Comment by CloCkWeRX** [comment]
Now #1111

**Pull request closed without merging**
