### PR TITLE
Check PR author is in CONTRIBUTORS.md under Travis

### PR DESCRIPTION
**Pull request by pozorvlak**
Results of testing this locally (the exit value of the last command is in my prompt):

```
0 $ TRAVIS=true TRAVIS_REPO_SLUG=growstuff/growstuff TRAVIS_PULL_REQUEST=1007 script/check_contributors_md
Checking to see if you're in CONTRIBUTORS.md...

Thanks for your contribution, ctlewitt!
Please add your name and GitHub handle to the file CONTRIBUTORS.md,
commit it, and update your PR.

1 $ TRAVIS=true TRAVIS_REPO_SLUG=growstuff/growstuff TRAVIS_PULL_REQUEST=1008 script/check_contributors_md
Checking to see if you're in CONTRIBUTORS.md...
- Miles Gould / [pozorvlak](https://github.com/pozorvlak)
0 $ script/check_contributors_md
Checking to see if you're in CONTRIBUTORS.md...
- Miles Gould / [pozorvlak](https://github.com/pozorvlak)
0 $
```

### CODE REVIEW

**Comment by maco** [comment]
"resubmit" might not be the right word to use. just committing/pushing
updates the current PR

**Comment by pozorvlak** [comment]
...and I forgot to commit the actual script. Good work there, self.

**Comment by CloCkWeRX** [comment]
Well, that will teach me to trust Travis...

```
bundler: failed to load command: script/check_contributors_md (script/check_contributors_md)
NoMethodError: undefined method `[]' for nil:NilClass
  script/check_contributors_md:11:in `<top (required)>'
```

**Comment by CloCkWeRX** [comment]
@pozorvlak pushed what should be a fix for it onto dev....

**Pull request merged**
