### PR TITLE
Release 50

### PR DESCRIPTION
**Pull request by Br3nda**
needs  #1780

### CODE REVIEW

**Comment by Br3nda** [comment]
needs #1765 so we can finish testing on staging

**Comment by cesy** [comment]
Needs a test on staging now we've got the email address bits fixed.

**Comment by Br3nda** [comment]
Let's merge # #1766 before we release this. There's some security patches in the gem bundle there.

**Comment by Br3nda** [comment]
This pull request **introduces 90 alerts** when merging f83a2b639730d985dc8fb38dd0caa6646404bee7 into 5c45beb54f43e58627dc375824f4ff59cf031166 - [view on LGTM.com](https://lgtm.com/projects/g/Growstuff/growstuff/rev/pr-c69cd48615a24d89ad4bf2f5b4188d3fe024e5ac)

**new alerts:**

* 64 for Duplicate variable declaration
* 12 for Conflicting variable initialization
* 6 for Useless assignment to local variable
* 3 for Useless conditional
* 3 for Superfluous trailing arguments
* 1 for Return statement assigns local variable
* 1 for Incomplete string escaping or encoding

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Br3nda** [comment]
I've turned off automatic deploys on Heroku. That's the feature where Heroku notices a change on a branch and deploy it. We don't use that - we use Travis to notice a branch change, run tests, then deploy.

I suspect Heroku enabled this for us when because it saw an app.json added to the branch. We'll need to watch it doesn't happen on production. If it does, we'll turn it off there too.

**Comment by Br3nda** [comment]
Rebased

**Comment by Br3nda** [comment]
blocked by #1780

**Comment by Br3nda** [comment]
My summer holiday has come to an end so I'm not sure when I'll have another big chunk of time to spend on it.

**Comment by Br3nda** [comment]
IT'S DEPLOYED

I've tested on staging.


Needs a green tick from someone, then we can put Rails5 live

**Pull request merged**
