### PR TITLE
Release 9

### PR DESCRIPTION
**Pull request by cesy**
This is what we have on staging that we'd want to put live - let's double-check it.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
I wonder if we need to jump straight to https://devcenter.heroku.com/articles/cedar-14-migration or are better served by intermediate releases (if there are any)

**Comment by CloCkWeRX** [comment]
@maco - the build errors are related to heroku deployment:
 
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.48.0/lib/excon/middlewares/expects.rb:10:in `response_call': Expected([200, 201]) <=> Actual(422 Unprocessable Entity) (Heroku::API::Errors::RequestFailed)
body: "{\"id\":\"invalid_params\",\"message\":\"Cedar-10 is deprecated. Please update to Cedar-14: https://devcenter.heroku.com/articles/cedar-14-migration\"}"
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.48.0/lib/excon/middlewares/response_parser.rb:8:in `response_call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.48.0/lib/excon/connection.rb:389:in `response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.48.0/lib/excon/connection.rb:253:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/heroku-api-0.4.2/lib/heroku/api.rb:84:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/provider/heroku/api.rb:95:in `post'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/provider/heroku/api.rb:33:in `trigger_build'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/provider/heroku/api.rb:13:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/provider.rb:145:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/provider.rb:145:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/provider/heroku/generic.rb:57:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.14/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by maco** [comment]
Oooh I just saw the angry red text about untracked files :) So we need to
merge the cedar change before anything else'll behave?

**Comment by CloCkWeRX** [comment]
Think so; though I have no idea what I'm doing with Heroku.

image

**Comment by CloCkWeRX** [comment]
@pozorvlak do you by chance have motive, means and opportunity to upgrade our Heroku deployment details?

https://devcenter.heroku.com/articles/cedar-14-migration covers the details and staging.growstuff.org is stuck in maintenance mode at the mo

**Comment by pozorvlak** [comment]
I have motive, and believe I have means; I'll try to find an opportunity :-)

**Comment by pozorvlak** [comment]
Done! Now let's see if I can re-run that failed build...

**Comment by pozorvlak** [comment]
Build restarted! [Now we play the waiting game...](https://www.youtube.com/watch?v=9JVNMmsN3Co)

**Comment by pozorvlak** [comment]
Passed!

**Comment by CloCkWeRX** [comment]
Alright, that seems happy.

I do have a few other security fixes (ruby 2.1.9, sigh) but this release seems a fair bit overdue. 

What level of testing do we want to do beyond the automated tests and "staging.growstuff.org isn't currently on fire" to get comfortable enough to do a production release?

**Comment by pozorvlak** [comment]
We should probably do some manual testing of the user-visible features
we're releasing, but I'm in favour of keeping it minimal - it's been far
too long since we did a production release.​

**Comment by maco** [comment]
Agreed

**Comment by CloCkWeRX** [comment]
Brief testing; unfortunately I think there's more work going to be needed.

Raised:
#847 #848 #849 #850 #851 #852 #853

Some are obviously not blocking, but others (progress bar behaviour, dropdowns having the wrong options now in a few places) seem like a definite regression from current production behaviour

**Comment by cesy** [comment]
http://talk.growstuff.org/t/needs-testing-first-half-of-release-9/283/5 also covers some of the manual testing that's been done.

**Comment by CloCkWeRX** [comment]
I think I've covered the rest of the stuff pending testing from http://talk.growstuff.org/t/needs-testing-first-half-of-release-9/283/5 - I don't think any of that is blocking; but we should triage it into issues for later probably.

I would be +1 to a release.

**Comment by cesy** [comment]
Yes, I think we're good to go as soon as we have two people with admin access around in case of disaster during deploy, then I'll press the button.

**Comment by CloCkWeRX** [comment]
One trillion tickets raised; they will need more love and attention to be super useful probably - screenshots and the like.

**Comment by pozorvlak** [comment]
I can be around this evening (GMT+1) - @cesy, does that work for you?

**Pull request merged**
