### PR TITLE
Release 21

### PR DESCRIPTION
**Pull request by cesy**
Keeping going with small frequent releases.

### CODE REVIEW

**Comment by cesy** [comment]
Let's get this out sooner rather than later? Just needs someone other than me to approve.

**Comment by Br3nda** [comment]
Signup is broken on staging

**Comment by Br3nda** [comment]
Password reset broken on staging too.

trying to test this release candidate.

**Comment by Br3nda** [comment]
Can anyone retrieve the error messages from staging?

**Comment by pozorvlak** [comment]
@Br3nda: I've added you (via your net.nz email address) as a collaborator on both staging and production, so you should now be able to retrieve logs with `heroku logs --app=growstuff-(prod|staging)`.

**Comment by pozorvlak** [comment]
Relevant part of logs:

```
app[web.1]: Completed 500 Internal Server Error in 1807ms (ActiveRecord: 22.6ms)
app[web.1]: 
app[web.1]: Net::SMTPFatalError (550 5.7.1 Unconfigured Sending Domain <growstuff.org>
app[web.1]: ):
app[web.1]:   vendor/ruby-2.3.3/lib/ruby/2.3.0/net/smtp.rb:965:in 'check_response'
[snip]
app[web.1]:   vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/lib/devise/models/confirmable.rb:117:in `send_confirmation_instructions'
app[web.1]:   vendor/bundle/ruby/2.3.0/gems/devise-4.2.0/lib/devise/models/confirmable.rb:179:in `send_on_create_confirmation_instructions'
```

**Comment by Br3nda** [comment]
email sending is broken on staging..

Also , staging is exceeding memory quota. error:
2017-03-16T00:38:43.648710+00:00 heroku[web.1]: Process running mem=536M(104.8%)
2017-03-16T00:38:43.648919+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)

I wanna look into that a bit more before releasing this.

**Comment by Br3nda** [comment]
This is constantly happening
```
2017-03-16T00:39:24.923696+00:00 heroku[web.1]: Process running mem=536M(104.8%)
2017-03-16T00:39:24.923745+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-03-16T00:39:46.311402+00:00 heroku[web.1]: Process running mem=536M(104.8%)
2017-03-16T00:39:46.311505+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-03-16T00:40:06.918950+00:00 heroku[web.1]: Process running mem=536M(104.8%)
2017-03-16T00:40:06.919055+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-03-16T00:40:28.238781+00:00 heroku[web.1]: Process running mem=536M(104.8%)
2017-03-16T00:40:28.238873+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

**Comment by cesy** [comment]
What else can we do to get staging stable?

**Comment by pozorvlak** [comment]
The push build is failing with the following error:

```
triggering new deployment
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.3.3
-----> Installing dependencies using bundler 1.13.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Your Ruby version is 2.3.3, but your Gemfile specified 2.3.4
       Bundler Output: Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Your Ruby version is 2.3.3, but your Gemfile specified 2.3.4
 !
 !     Failed to install gems via Bundler.
 !     Detected a mismatch between your Ruby version installed and
 !     Ruby version specified in Gemfile or Gemfile.lock:
 !     https://devcenter.heroku.com/articles/ruby-versions#your-ruby-version-is-x-but-your-gemfile-specified-y
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
Already up-to-date!
```
Weird. Re-running.

**Comment by Br3nda** [comment]
"       Your Ruby version is 2.3.3, but your Gemfile specified 2.3.4"

**Comment by Br3nda** [comment]
I'd love someone to review #1299 so we can see if this fixes t deployment problem.

**Comment by Br3nda** [comment]
New error. it's aparently checking node_modules.

**Comment by Br3nda** [comment]
disabling eslint here  #1303

**Comment by Br3nda** [comment]
Staging looks good now

**Comment by Br3nda** [comment]
Looks good on prod

**Pull request merged**
